// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_PERSONAL_INCALL
void ui_PERSONAL_INCALL_screen_init(void);
lv_obj_t * ui_PERSONAL_INCALL;
lv_obj_t * ui_server_on3;
lv_obj_t * ui_Peta_FF3;
lv_obj_t * ui_Waktu3;
lv_obj_t * ui_Sound3;
lv_obj_t * ui_Brightness3;
lv_obj_t * ui_Setting3;
lv_obj_t * ui_Button_Personal3;
lv_obj_t * ui_Buton_Group3;
lv_obj_t * ui_Button_Radio3;
lv_obj_t * ui_logo_Intercom3;
lv_obj_t * ui_list_Personal_incall;
lv_obj_t * ui_Kom_Anjungan_incall;
lv_obj_t * ui_Palaksan_Anjungan_incall;
lv_obj_t * ui_CIC_ROOM_incall;
lv_obj_t * ui_ECR_KA__incall;
lv_obj_t * ui_ECR_KI_incall;
lv_obj_t * ui_empty1_incall;
lv_obj_t * ui_empty2_incall;
lv_obj_t * ui_empty3_incall;
lv_obj_t * ui_empty4_incall;
lv_obj_t * ui_empty5_incall;
lv_obj_t * ui_empty6_incall;
lv_obj_t * ui_empty7_incall;
lv_obj_t * ui_empty8_incall;
lv_obj_t * ui_empty9_incall;
lv_obj_t * ui_empty10_incall;
lv_obj_t * ui_empty11_incall;
lv_obj_t * ui_empty12_incall;
lv_obj_t * ui_empty13_incall;
lv_obj_t * ui_empty14_incall;
lv_obj_t * ui_empty15_incall;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_button_[1] = {&ui_img_button_14_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_PERSONAL_INCALL_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    // lv_disp_load_scr(ui_PERSONAL_INCALL);
}
