// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_PERSONAL_INCALL
void ui_PERSONAL_INCALL_screen_init(void);
extern lv_obj_t * ui_PERSONAL_INCALL;
extern lv_obj_t * ui_server_on3;
extern lv_obj_t * ui_Peta_FF3;
extern lv_obj_t * ui_Waktu3;
extern lv_obj_t * ui_Sound3;
extern lv_obj_t * ui_Brightness3;
extern lv_obj_t * ui_Setting3;
extern lv_obj_t * ui_Button_Personal3;
extern lv_obj_t * ui_Buton_Group3;
extern lv_obj_t * ui_Button_Radio3;
extern lv_obj_t * ui_logo_Intercom3;
extern lv_obj_t * ui_list_Personal_incall;
extern lv_obj_t * ui_Kom_Anjungan_incall;
extern lv_obj_t * ui_Palaksan_Anjungan_incall;
extern lv_obj_t * ui_CIC_ROOM_incall;
extern lv_obj_t * ui_ECR_KA__incall;
extern lv_obj_t * ui_ECR_KI_incall;
extern lv_obj_t * ui_empty1_incall;
extern lv_obj_t * ui_empty2_incall;
extern lv_obj_t * ui_empty3_incall;
extern lv_obj_t * ui_empty4_incall;
extern lv_obj_t * ui_empty5_incall;
extern lv_obj_t * ui_empty6_incall;
extern lv_obj_t * ui_empty7_incall;
extern lv_obj_t * ui_empty8_incall;
extern lv_obj_t * ui_empty9_incall;
extern lv_obj_t * ui_empty10_incall;
extern lv_obj_t * ui_empty11_incall;
extern lv_obj_t * ui_empty12_incall;
extern lv_obj_t * ui_empty13_incall;
extern lv_obj_t * ui_empty14_incall;
extern lv_obj_t * ui_empty15_incall;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_1200060910);    // assets/ci_settings-filled.png
LV_IMG_DECLARE(ui_img_personal_buttonn_png);    // assets/PERSONAL BUTTONN.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radiopa_button_png);    // assets/RADIOPA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png
LV_IMG_DECLARE(ui_img_list_personal_incall_png);    // assets/List Personal Incall.png
LV_IMG_DECLARE(ui_img_button_kom_anjgan_incall_png);    // assets/BUTTON KOM ANJGAN INCALL.png
LV_IMG_DECLARE(ui_img_button_palaksa_incall_png);    // assets/BUTTON PALAKSA INCALL.png
LV_IMG_DECLARE(ui_img_button_cic_room_incall_png);    // assets/BUTTON CIC ROOM INCALL.png
LV_IMG_DECLARE(ui_img_button_ecr_ka_incall_png);    // assets/BUTTON ECR KA INCALL.png
LV_IMG_DECLARE(ui_img_button_ecr_ki_incall_png);    // assets/BUTTON ECR KI INCALL.png
LV_IMG_DECLARE(ui_img_button_14_png);    // assets/Button_14.png

LV_FONT_DECLARE(ui_font_CPU);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_MHz);
LV_FONT_DECLARE(ui_font_about);
LV_FONT_DECLARE(ui_font_pabx);
LV_FONT_DECLARE(ui_font_roboto_medium);
LV_FONT_DECLARE(ui_font_setting);
LV_FONT_DECLARE(ui_font_value);
LV_FONT_DECLARE(ui_font_volume);
LV_FONT_DECLARE(ui_font_waktu);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
