// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_ABOUT_screen_init(void)
{
    ui_ABOUT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ABOUT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ABOUT, lv_color_hex(0x1480BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ABOUT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ABOUT, lv_color_hex(0x03303C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ABOUT, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_server_on10 = lv_imgbtn_create(ui_ABOUT);
    lv_imgbtn_set_src(ui_server_on10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lucide_server_png, NULL);
    lv_obj_set_height(ui_server_on10, 28);
    lv_obj_set_width(ui_server_on10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_server_on10, 20);
    lv_obj_set_y(ui_server_on10, 14);

    ui_Peta_FF10 = lv_label_create(ui_ABOUT);
    lv_obj_set_width(ui_Peta_FF10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peta_FF10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peta_FF10, 51);
    lv_obj_set_y(ui_Peta_FF10, 14);
    lv_label_set_text(ui_Peta_FF10, "PETA FF");
    lv_obj_set_style_text_color(ui_Peta_FF10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Peta_FF10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Peta_FF10, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waktu10 = lv_label_create(ui_ABOUT);
    lv_obj_set_width(ui_Waktu10, 73);
    lv_obj_set_height(ui_Waktu10, 33);
    lv_obj_set_x(ui_Waktu10, 436);
    lv_obj_set_y(ui_Waktu10, 16);
    lv_label_set_text(ui_Waktu10, "08:00");
    lv_obj_set_style_text_color(ui_Waktu10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waktu10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waktu10, &ui_font_waktu, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sound10 = lv_imgbtn_create(ui_ABOUT);
    lv_imgbtn_set_src(ui_Sound10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1559931635, NULL);
    lv_obj_set_width(ui_Sound10, 40);
    lv_obj_set_height(ui_Sound10, 40);
    lv_obj_set_x(ui_Sound10, 518);
    lv_obj_set_y(ui_Sound10, 8);

    ui_Brightness10 = lv_imgbtn_create(ui_ABOUT);
    lv_imgbtn_set_src(ui_Brightness10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_388315622, NULL);
    lv_obj_set_width(ui_Brightness10, 50);
    lv_obj_set_height(ui_Brightness10, 50);
    lv_obj_set_x(ui_Brightness10, 567);
    lv_obj_set_y(ui_Brightness10, 3);

    ui_Setting10 = lv_imgbtn_create(ui_ABOUT);
    lv_imgbtn_set_src(ui_Setting10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_111514558, NULL);
    lv_obj_set_width(ui_Setting10, 40);
    lv_obj_set_height(ui_Setting10, 39);
    lv_obj_set_x(ui_Setting10, 626);
    lv_obj_set_y(ui_Setting10, 8);

    ui_Personal_setting10 = lv_imgbtn_create(ui_ABOUT);
    lv_imgbtn_set_src(ui_Personal_setting10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_personal_button_png, NULL);
    lv_obj_set_width(ui_Personal_setting10, 80);
    lv_obj_set_height(ui_Personal_setting10, 100);
    lv_obj_set_x(ui_Personal_setting10, 711);
    lv_obj_set_y(ui_Personal_setting10, 65);

    ui_Group_setting10 = lv_imgbtn_create(ui_ABOUT);
    lv_imgbtn_set_src(ui_Group_setting10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_button_png, NULL);
    lv_obj_set_width(ui_Group_setting10, 80);
    lv_obj_set_height(ui_Group_setting10, 100);
    lv_obj_set_x(ui_Group_setting10, 711);
    lv_obj_set_y(ui_Group_setting10, 195);

    ui_radio_setting10 = lv_imgbtn_create(ui_ABOUT);
    lv_imgbtn_set_src(ui_radio_setting10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radiopa_button_png, NULL);
    lv_obj_set_width(ui_radio_setting10, 80);
    lv_obj_set_height(ui_radio_setting10, 120);
    lv_obj_set_x(ui_radio_setting10, 712);
    lv_obj_set_y(ui_radio_setting10, 320);

    ui_logo_intercom10 = lv_img_create(ui_ABOUT);
    lv_img_set_src(ui_logo_intercom10, &ui_img_logo_navysis_png);
    lv_obj_set_width(ui_logo_intercom10, LV_SIZE_CONTENT);   /// 613
    lv_obj_set_height(ui_logo_intercom10, LV_SIZE_CONTENT);    /// 248
    lv_obj_set_align(ui_logo_intercom10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_intercom10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_intercom10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_popup_setting10 = lv_img_create(ui_ABOUT);
    lv_img_set_src(ui_popup_setting10, &ui_img_popup_set_png);
    lv_obj_set_width(ui_popup_setting10, LV_SIZE_CONTENT);   /// 685
    lv_obj_set_height(ui_popup_setting10, LV_SIZE_CONTENT);    /// 405
    lv_obj_set_x(ui_popup_setting10, 10);
    lv_obj_set_y(ui_popup_setting10, 64);
    lv_obj_add_flag(ui_popup_setting10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_popup_setting10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Setting10 = lv_label_create(ui_popup_setting10);
    lv_obj_set_width(ui_Label_Setting10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Setting10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Setting10, 20);
    lv_obj_set_y(ui_Label_Setting10, 22);
    lv_label_set_text(ui_Label_Setting10, "SETTING");
    lv_obj_set_style_text_color(ui_Label_Setting10, lv_color_hex(0x234A81), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Setting10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Setting10, &ui_font_pabx, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Performance2 = lv_imgbtn_create(ui_popup_setting10);
    lv_imgbtn_set_src(ui_Button_Performance2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_430847109, NULL);
    lv_obj_set_width(ui_Button_Performance2, 100);
    lv_obj_set_height(ui_Button_Performance2, 30);
    lv_obj_set_x(ui_Button_Performance2, 23);
    lv_obj_set_y(ui_Button_Performance2, 54);

    ui_Button_Selftest2 = lv_imgbtn_create(ui_popup_setting10);
    lv_imgbtn_set_src(ui_Button_Selftest2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1693904590, NULL);
    lv_obj_set_width(ui_Button_Selftest2, 100);
    lv_obj_set_height(ui_Button_Selftest2, 30);
    lv_obj_set_x(ui_Button_Selftest2, 123);
    lv_obj_set_y(ui_Button_Selftest2, 54);

    ui_Button_About2 = lv_imgbtn_create(ui_popup_setting10);
    lv_imgbtn_set_src(ui_Button_About2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_650324235, NULL);
    lv_obj_set_width(ui_Button_About2, 100);
    lv_obj_set_height(ui_Button_About2, 30);
    lv_obj_set_x(ui_Button_About2, 223);
    lv_obj_set_y(ui_Button_About2, 54);

    ui_Label_Information = lv_label_create(ui_popup_setting10);
    lv_obj_set_width(ui_Label_Information, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Information, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Information, 40);
    lv_obj_set_y(ui_Label_Information, 100);
    lv_label_set_text(ui_Label_Information, "Information Software Voice Intercom Naval System");
    lv_obj_set_style_text_font(ui_Label_Information, &ui_font_volume, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_software = lv_label_create(ui_popup_setting10);
    lv_obj_set_width(ui_Label_software, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_software, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_software, 40);
    lv_obj_set_y(ui_Label_software, 130);
    lv_label_set_text(ui_Label_software,
                      "The Software Voice Intercom Naval System is a design and implementation \nfor a naval communication system.\n\ndesigning a user interface for the Software Voice Intercom Naval System using\nthe Light and Versatile Embedded Graphics Library (LVGL) and Squareline Studio tools.\nThe user interface design process revolves around utilizing pre-designed widgets and user interface\ncontrol in the form of Figma designs");
    lv_obj_set_style_text_font(ui_Label_software, &ui_font_about, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Version = lv_label_create(ui_popup_setting10);
    lv_obj_set_width(ui_Label_Version, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Version, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Version, 40);
    lv_obj_set_y(ui_Label_Version, 246);
    lv_label_set_text(ui_Label_Version, "Software Version");
    lv_obj_set_style_text_font(ui_Label_Version, &ui_font_volume, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_img_create(ui_popup_setting10);
    lv_img_set_src(ui_logo, &ui_img_1015138501);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 303
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 58
    lv_obj_set_x(ui_logo, 209);
    lv_obj_set_y(ui_logo, 167);
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_value_versi = lv_label_create(ui_popup_setting10);
    lv_obj_set_width(ui_value_versi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value_versi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value_versi, 40);
    lv_obj_set_y(ui_value_versi, 272);
    lv_label_set_text(ui_value_versi, "1.0.0.0");
    lv_obj_set_style_text_font(ui_value_versi, &ui_font_about, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button_Performance2, ui_event_Button_Performance2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Selftest2, ui_event_Button_Selftest2, LV_EVENT_ALL, NULL); 
    lv_obj_add_event_cb(ui_Button_About2, ui_event_Button_About2, LV_EVENT_ALL, NULL);
    

}
