// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_BRIGHTNESS_screen_init(void)
{
    ui_BRIGHTNESS = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BRIGHTNESS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BRIGHTNESS, lv_color_hex(0x1480BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BRIGHTNESS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BRIGHTNESS, lv_color_hex(0x03303C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BRIGHTNESS, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_server_on7 = lv_imgbtn_create(ui_BRIGHTNESS);
    lv_imgbtn_set_src(ui_server_on7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lucide_server_png, NULL);
    lv_obj_set_height(ui_server_on7, 28);
    lv_obj_set_width(ui_server_on7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_server_on7, 20);
    lv_obj_set_y(ui_server_on7, 14);

    ui_Peta_FF7 = lv_label_create(ui_BRIGHTNESS);
    lv_obj_set_width(ui_Peta_FF7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peta_FF7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peta_FF7, 51);
    lv_obj_set_y(ui_Peta_FF7, 14);
    lv_label_set_text(ui_Peta_FF7, "PETA FF");
    lv_obj_set_style_text_color(ui_Peta_FF7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Peta_FF7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Peta_FF7, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waktu7 = lv_label_create(ui_BRIGHTNESS);
    lv_obj_set_width(ui_Waktu7, 73);
    lv_obj_set_height(ui_Waktu7, 33);
    lv_obj_set_x(ui_Waktu7, 436);
    lv_obj_set_y(ui_Waktu7, 16);
    lv_label_set_text(ui_Waktu7, "08:00");
    lv_obj_set_style_text_color(ui_Waktu7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waktu7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waktu7, &ui_font_waktu, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sound7 = lv_imgbtn_create(ui_BRIGHTNESS);
    lv_imgbtn_set_src(ui_Sound7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1559931635, NULL);
    lv_obj_set_width(ui_Sound7, 40);
    lv_obj_set_height(ui_Sound7, 40);
    lv_obj_set_x(ui_Sound7, 518);
    lv_obj_set_y(ui_Sound7, 8);

    ui_Brightness7 = lv_imgbtn_create(ui_BRIGHTNESS);
    lv_imgbtn_set_src(ui_Brightness7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_brightness_png, NULL);
    lv_obj_set_width(ui_Brightness7, 50);
    lv_obj_set_height(ui_Brightness7, 50);
    lv_obj_set_x(ui_Brightness7, 567);
    lv_obj_set_y(ui_Brightness7, 3);

    ui_Setting7 = lv_imgbtn_create(ui_BRIGHTNESS);
    lv_imgbtn_set_src(ui_Setting7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1200060910, NULL);
    lv_obj_set_width(ui_Setting7, 40);
    lv_obj_set_height(ui_Setting7, 39);
    lv_obj_set_x(ui_Setting7, 626);
    lv_obj_set_y(ui_Setting7, 8);

    ui_Personal_brightness = lv_imgbtn_create(ui_BRIGHTNESS);
    lv_imgbtn_set_src(ui_Personal_brightness, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_personal_button_png, NULL);
    lv_obj_set_width(ui_Personal_brightness, 80);
    lv_obj_set_height(ui_Personal_brightness, 100);
    lv_obj_set_x(ui_Personal_brightness, 711);
    lv_obj_set_y(ui_Personal_brightness, 65);

    ui_Group_brightness = lv_imgbtn_create(ui_BRIGHTNESS);
    lv_imgbtn_set_src(ui_Group_brightness, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_button_png, NULL);
    lv_obj_set_width(ui_Group_brightness, 80);
    lv_obj_set_height(ui_Group_brightness, 100);
    lv_obj_set_x(ui_Group_brightness, 711);
    lv_obj_set_y(ui_Group_brightness, 195);

    ui_radio_brightness = lv_imgbtn_create(ui_BRIGHTNESS);
    lv_imgbtn_set_src(ui_radio_brightness, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radiopa_button_png, NULL);
    lv_obj_set_width(ui_radio_brightness, 80);
    lv_obj_set_height(ui_radio_brightness, 120);
    lv_obj_set_x(ui_radio_brightness, 712);
    lv_obj_set_y(ui_radio_brightness, 320);

    ui_logo_intercom_7 = lv_img_create(ui_BRIGHTNESS);
    lv_img_set_src(ui_logo_intercom_7, &ui_img_logo_navysis_png);
    lv_obj_set_width(ui_logo_intercom_7, LV_SIZE_CONTENT);   /// 613
    lv_obj_set_height(ui_logo_intercom_7, LV_SIZE_CONTENT);    /// 248
    lv_obj_set_align(ui_logo_intercom_7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_intercom_7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_intercom_7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_popup_brightness = lv_img_create(ui_BRIGHTNESS);
    lv_img_set_src(ui_popup_brightness, &ui_img_popup_volume_updown_png);
    lv_obj_set_width(ui_popup_brightness, LV_SIZE_CONTENT);   /// 450
    lv_obj_set_height(ui_popup_brightness, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_popup_brightness, 175);
    lv_obj_set_y(ui_popup_brightness, 90);
    lv_obj_add_flag(ui_popup_brightness, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_popup_brightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_brightness = lv_label_create(ui_popup_brightness);
    lv_obj_set_width(ui_Label_brightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_brightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_brightness, 19);
    lv_obj_set_y(ui_Label_brightness, 10);
    lv_label_set_text(ui_Label_brightness, "Brightness");
    lv_obj_set_style_text_color(ui_Label_brightness, lv_color_hex(0x234A81), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_brightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_brightness, &ui_font_volume, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Adjust_Brightness = lv_slider_create(ui_popup_brightness);
    lv_slider_set_value(ui_Adjust_Brightness, 72, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Adjust_Brightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Adjust_Brightness, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_Adjust_Brightness, 298);
    lv_obj_set_height(ui_Adjust_Brightness, 10);
    lv_obj_set_x(ui_Adjust_Brightness, 57);
    lv_obj_set_y(ui_Adjust_Brightness, 52);
    lv_obj_set_style_bg_color(ui_Adjust_Brightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Adjust_Brightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Adjust_Brightness, lv_color_hex(0x426392), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Adjust_Brightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Adjust_Brightness, lv_color_hex(0x234A81), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Adjust_Brightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_value_brightness = lv_label_create(ui_popup_brightness);
    lv_obj_set_width(ui_value_brightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value_brightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value_brightness, 403);
    lv_obj_set_y(ui_value_brightness, 45);
    lv_label_set_text(ui_value_brightness, "72");
    lv_obj_set_style_text_color(ui_value_brightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_value_brightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_value_brightness, &ui_font_value, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttov_plus_brightness = lv_imgbtn_create(ui_popup_brightness);
    lv_imgbtn_set_src(ui_buttov_plus_brightness, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_154043135, NULL);
    lv_obj_set_width(ui_buttov_plus_brightness, 24);
    lv_obj_set_height(ui_buttov_plus_brightness, 24);
    lv_obj_set_x(ui_buttov_plus_brightness, 370);
    lv_obj_set_y(ui_buttov_plus_brightness, 45);

    ui_buttov_min_brightness = lv_imgbtn_create(ui_popup_brightness);
    lv_imgbtn_set_src(ui_buttov_min_brightness, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1738235521, NULL);
    lv_obj_set_width(ui_buttov_min_brightness, 24);
    lv_obj_set_height(ui_buttov_min_brightness, 24);
    lv_obj_set_x(ui_buttov_min_brightness, 18);
    lv_obj_set_y(ui_buttov_min_brightness, 45);

    ui_close_brightness = lv_imgbtn_create(ui_popup_brightness);
    lv_imgbtn_set_src(ui_close_brightness, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2126526304, NULL);
    lv_obj_set_width(ui_close_brightness, 30);
    lv_obj_set_height(ui_close_brightness, 30);
    lv_obj_set_x(ui_close_brightness, 415);
    lv_obj_set_y(ui_close_brightness, 5);

    lv_obj_add_event_cb(ui_Adjust_Brightness, ui_event_Adjust_Brightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Brightness7, ui_event_Brightness7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Adjust_Brightness, ui_event_Adjust_Brightness_changed_callback, LV_EVENT_ALL,NULL);
    lv_obj_add_event_cb(ui_buttov_plus_brightness, ui_event_buttov_plus_brightness_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_buttov_min_brightness, ui_event_buttov_min_brightness_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_close_brightness, ui_event_close_brightness_clicked, LV_EVENT_CLICKED, NULL);

}
