// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_GROUP_SELECT_screen_init(void)
{
    ui_GROUP_SELECT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GROUP_SELECT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GROUP_SELECT, lv_color_hex(0x1480BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GROUP_SELECT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_GROUP_SELECT, lv_color_hex(0x03303C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_GROUP_SELECT, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_server_on4 = lv_imgbtn_create(ui_GROUP_SELECT);
    lv_imgbtn_set_src(ui_server_on4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lucide_server_png, NULL);
    lv_obj_set_height(ui_server_on4, 28);
    lv_obj_set_width(ui_server_on4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_server_on4, 20);
    lv_obj_set_y(ui_server_on4, 14);

    ui_Peta_FF4 = lv_label_create(ui_GROUP_SELECT);
    lv_obj_set_width(ui_Peta_FF4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peta_FF4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peta_FF4, 51);
    lv_obj_set_y(ui_Peta_FF4, 14);
    lv_label_set_text(ui_Peta_FF4, "PETA FF");
    lv_obj_set_style_text_color(ui_Peta_FF4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Peta_FF4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Peta_FF4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waktu4 = lv_label_create(ui_GROUP_SELECT);
    lv_obj_set_width(ui_Waktu4, 73);
    lv_obj_set_height(ui_Waktu4, 33);
    lv_obj_set_x(ui_Waktu4, 436);
    lv_obj_set_y(ui_Waktu4, 16);
    lv_label_set_text(ui_Waktu4, "08:00");
    lv_obj_set_style_text_color(ui_Waktu4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waktu4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waktu4, &ui_font_waktu, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sound4 = lv_imgbtn_create(ui_GROUP_SELECT);
    lv_imgbtn_set_src(ui_Sound4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1559931635, NULL);
    lv_obj_set_width(ui_Sound4, 40);
    lv_obj_set_height(ui_Sound4, 40);
    lv_obj_set_x(ui_Sound4, 518);
    lv_obj_set_y(ui_Sound4, 8);

    ui_Brightness4 = lv_imgbtn_create(ui_GROUP_SELECT);
    lv_imgbtn_set_src(ui_Brightness4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_388315622, NULL);
    lv_obj_set_width(ui_Brightness4, 50);
    lv_obj_set_height(ui_Brightness4, 50);
    lv_obj_set_x(ui_Brightness4, 567);
    lv_obj_set_y(ui_Brightness4, 3);

    ui_Setting4 = lv_imgbtn_create(ui_GROUP_SELECT);
    lv_imgbtn_set_src(ui_Setting4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1200060910, NULL);
    lv_obj_set_width(ui_Setting4, 40);
    lv_obj_set_height(ui_Setting4, 39);
    lv_obj_set_x(ui_Setting4, 626);
    lv_obj_set_y(ui_Setting4, 8);

    ui_Personal_group = lv_imgbtn_create(ui_GROUP_SELECT);
    lv_imgbtn_set_src(ui_Personal_group, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_personal_button_select_png, NULL);
    lv_obj_set_width(ui_Personal_group, 80);
    lv_obj_set_height(ui_Personal_group, 100);
    lv_obj_set_x(ui_Personal_group, 711);
    lv_obj_set_y(ui_Personal_group, 65);

    ui_Group_Select = lv_imgbtn_create(ui_GROUP_SELECT);
    lv_imgbtn_set_src(ui_Group_Select, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_button_png, NULL);
    lv_obj_set_width(ui_Group_Select, 80);
    lv_obj_set_height(ui_Group_Select, 100);
    lv_obj_set_x(ui_Group_Select, 711);
    lv_obj_set_y(ui_Group_Select, 195);

    ui_Radio_Group = lv_imgbtn_create(ui_GROUP_SELECT);
    lv_imgbtn_set_src(ui_Radio_Group, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radiopa_button_png, NULL);
    lv_obj_set_width(ui_Radio_Group, 80);
    lv_obj_set_height(ui_Radio_Group, 120);
    lv_obj_set_x(ui_Radio_Group, 712);
    lv_obj_set_y(ui_Radio_Group, 320);

    ui_logo_intercom_4 = lv_img_create(ui_GROUP_SELECT);
    lv_img_set_src(ui_logo_intercom_4, &ui_img_logo_navysis_png);
    lv_obj_set_width(ui_logo_intercom_4, LV_SIZE_CONTENT);   /// 613
    lv_obj_set_height(ui_logo_intercom_4, LV_SIZE_CONTENT);    /// 248
    lv_obj_set_align(ui_logo_intercom_4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_intercom_4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_intercom_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_list_personal_group = lv_img_create(ui_GROUP_SELECT);
    lv_img_set_src(ui_list_personal_group, &ui_img_list_group_png);
    lv_obj_set_width(ui_list_personal_group, LV_SIZE_CONTENT);   /// 685
    lv_obj_set_height(ui_list_personal_group, LV_SIZE_CONTENT);    /// 415
    lv_obj_set_x(ui_list_personal_group, 7);
    lv_obj_set_y(ui_list_personal_group, 57);
    lv_obj_add_flag(ui_list_personal_group, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_list_personal_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_group_pku = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_group_pku, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_8_png, NULL);
    lv_obj_set_width(ui_group_pku, 110);
    lv_obj_set_height(ui_group_pku, 100);

    ui_group_pk_sen = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_group_pk_sen, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_2_png, NULL);
    lv_obj_set_width(ui_group_pk_sen, 110);
    lv_obj_set_height(ui_group_pk_sen, 100);
    lv_obj_set_x(ui_group_pk_sen, 115);
    lv_obj_set_y(ui_group_pk_sen, 0);

    ui_group_pk_ops = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_group_pk_ops, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_3_png, NULL);
    lv_obj_set_width(ui_group_pk_ops, 110);
    lv_obj_set_height(ui_group_pk_ops, 100);
    lv_obj_set_x(ui_group_pk_ops, 230);
    lv_obj_set_y(ui_group_pk_ops, 0);

    ui_group_manuvra = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_group_manuvra, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_4_png, NULL);
    lv_obj_set_width(ui_group_manuvra, 110);
    lv_obj_set_height(ui_group_manuvra, 100);
    lv_obj_set_x(ui_group_manuvra, 345);
    lv_obj_set_y(ui_group_manuvra, 0);

    ui_group_pit = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_group_pit, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_5_png, NULL);
    lv_obj_set_width(ui_group_pit, 110);
    lv_obj_set_height(ui_group_pit, 100);
    lv_obj_set_x(ui_group_pit, 460);
    lv_obj_set_y(ui_group_pit, 0);

    ui_group_all = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_group_all, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_6_png, NULL);
    lv_obj_set_width(ui_group_all, 110);
    lv_obj_set_height(ui_group_all, 100);
    lv_obj_set_x(ui_group_all, 575);
    lv_obj_set_y(ui_group_all, 0);

    ui_empty_group_select1 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_1__png, NULL);
    lv_obj_set_width(ui_empty_group_select1, 110);
    lv_obj_set_height(ui_empty_group_select1, 100);
    lv_obj_set_x(ui_empty_group_select1, 0);
    lv_obj_set_y(ui_empty_group_select1, 105);

    ui_empty_group_select2 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_2_png, NULL);
    lv_obj_set_width(ui_empty_group_select2, 110);
    lv_obj_set_height(ui_empty_group_select2, 100);
    lv_obj_set_x(ui_empty_group_select2, 115);
    lv_obj_set_y(ui_empty_group_select2, 105);

    ui_empty_group_select3 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_3_png, NULL);
    lv_obj_set_width(ui_empty_group_select3, 110);
    lv_obj_set_height(ui_empty_group_select3, 100);
    lv_obj_set_x(ui_empty_group_select3, 230);
    lv_obj_set_y(ui_empty_group_select3, 105);

    ui_empty_group_select4 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_4_png, NULL);
    lv_obj_set_width(ui_empty_group_select4, 110);
    lv_obj_set_height(ui_empty_group_select4, 100);
    lv_obj_set_x(ui_empty_group_select4, 345);
    lv_obj_set_y(ui_empty_group_select4, 105);

    ui_empty_group_select5 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_5_png, NULL);
    lv_obj_set_width(ui_empty_group_select5, 110);
    lv_obj_set_height(ui_empty_group_select5, 100);
    lv_obj_set_x(ui_empty_group_select5, 460);
    lv_obj_set_y(ui_empty_group_select5, 105);

    ui_empty_group_select6 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_6__png, NULL);
    lv_obj_set_width(ui_empty_group_select6, 110);
    lv_obj_set_height(ui_empty_group_select6, 100);
    lv_obj_set_x(ui_empty_group_select6, 575);
    lv_obj_set_y(ui_empty_group_select6, 105);

    ui_empty_group_select7 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_7_png, NULL);
    lv_obj_set_width(ui_empty_group_select7, 110);
    lv_obj_set_height(ui_empty_group_select7, 100);
    lv_obj_set_x(ui_empty_group_select7, 0);
    lv_obj_set_y(ui_empty_group_select7, 210);

    ui_empty_group_select8 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_8_png, NULL);
    lv_obj_set_width(ui_empty_group_select8, 110);
    lv_obj_set_height(ui_empty_group_select8, 100);
    lv_obj_set_x(ui_empty_group_select8, 115);
    lv_obj_set_y(ui_empty_group_select8, 210);

    ui_empty_group_select9 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_9_png, NULL);
    lv_obj_set_width(ui_empty_group_select9, 110);
    lv_obj_set_height(ui_empty_group_select9, 100);
    lv_obj_set_x(ui_empty_group_select9, 230);
    lv_obj_set_y(ui_empty_group_select9, 210);

    ui_empty_group_select10 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_10_png, NULL);
    lv_obj_set_width(ui_empty_group_select10, 110);
    lv_obj_set_height(ui_empty_group_select10, 100);
    lv_obj_set_x(ui_empty_group_select10, 345);
    lv_obj_set_y(ui_empty_group_select10, 210);

    ui_empty_group_select11 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_11_png, NULL);
    lv_obj_set_width(ui_empty_group_select11, 110);
    lv_obj_set_height(ui_empty_group_select11, 100);
    lv_obj_set_x(ui_empty_group_select11, 460);
    lv_obj_set_y(ui_empty_group_select11, 210);

    ui_empty_group_select12 = lv_imgbtn_create(ui_list_personal_group);
    lv_imgbtn_set_src(ui_empty_group_select12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_12_png, NULL);
    lv_obj_set_width(ui_empty_group_select12, 110);
    lv_obj_set_height(ui_empty_group_select12, 100);
    lv_obj_set_x(ui_empty_group_select12, 575);
    lv_obj_set_y(ui_empty_group_select12, 210);

    // lv_obj_add_event_cb(ui_Sound4, ui_event_Sound4, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_Brightness4, ui_event_Brightness4, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_Setting4, ui_event_Setting4, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_Personal_group, ui_event_Personal_group, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_Group_Select, ui_event_Group_Select, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_Radio_Group, ui_event_Radio_Group, LV_EVENT_ALL, NULL);
    


}
