// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_PERSONAL_CALL_screen_init(void)
{
    ui_PERSONAL_CALL = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PERSONAL_CALL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PERSONAL_CALL, lv_color_hex(0x1480BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERSONAL_CALL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PERSONAL_CALL, lv_color_hex(0x03303C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PERSONAL_CALL, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_server_on2 = lv_imgbtn_create(ui_PERSONAL_CALL);
    lv_imgbtn_set_src(ui_server_on2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lucide_server_png, NULL);
    lv_obj_set_height(ui_server_on2, 28);
    lv_obj_set_width(ui_server_on2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_server_on2, 20);
    lv_obj_set_y(ui_server_on2, 14);

    ui_Peta_FF2 = lv_label_create(ui_PERSONAL_CALL);
    lv_obj_set_width(ui_Peta_FF2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peta_FF2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peta_FF2, 51);
    lv_obj_set_y(ui_Peta_FF2, 14);
    lv_label_set_text(ui_Peta_FF2, "PETA FF");
    lv_obj_set_style_text_color(ui_Peta_FF2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Peta_FF2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Peta_FF2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waktu2 = lv_label_create(ui_PERSONAL_CALL);
    lv_obj_set_width(ui_Waktu2, 73);
    lv_obj_set_height(ui_Waktu2, 33);
    lv_obj_set_x(ui_Waktu2, 436);
    lv_obj_set_y(ui_Waktu2, 16);
    lv_label_set_text(ui_Waktu2, "08:00");
    lv_obj_set_style_text_color(ui_Waktu2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waktu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waktu2, &ui_font_waktu, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sound2 = lv_imgbtn_create(ui_PERSONAL_CALL);
    lv_imgbtn_set_src(ui_Sound2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1559931635, NULL);
    lv_obj_set_width(ui_Sound2, 40);
    lv_obj_set_height(ui_Sound2, 40);
    lv_obj_set_x(ui_Sound2, 518);
    lv_obj_set_y(ui_Sound2, 8);

    ui_Brightness2 = lv_imgbtn_create(ui_PERSONAL_CALL);
    lv_imgbtn_set_src(ui_Brightness2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_388315622, NULL);
    lv_obj_set_width(ui_Brightness2, 50);
    lv_obj_set_height(ui_Brightness2, 50);
    lv_obj_set_x(ui_Brightness2, 567);
    lv_obj_set_y(ui_Brightness2, 3);

    ui_Setting2 = lv_imgbtn_create(ui_PERSONAL_CALL);
    lv_imgbtn_set_src(ui_Setting2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1200060910, NULL);
    lv_obj_set_width(ui_Setting2, 40);
    lv_obj_set_height(ui_Setting2, 39);
    lv_obj_set_x(ui_Setting2, 626);
    lv_obj_set_y(ui_Setting2, 8);

    ui_Button_Personal2 = lv_imgbtn_create(ui_PERSONAL_CALL);
    lv_imgbtn_set_src(ui_Button_Personal2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_personal_buttonn_png, NULL);
    lv_obj_set_width(ui_Button_Personal2, 80);
    lv_obj_set_height(ui_Button_Personal2, 100);
    lv_obj_set_x(ui_Button_Personal2, 711);
    lv_obj_set_y(ui_Button_Personal2, 65);

    ui_Button_Group2 = lv_imgbtn_create(ui_PERSONAL_CALL);
    lv_imgbtn_set_src(ui_Button_Group2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_button_png, NULL);
    lv_obj_set_width(ui_Button_Group2, 80);
    lv_obj_set_height(ui_Button_Group2, 100);
    lv_obj_set_x(ui_Button_Group2, 711);
    lv_obj_set_y(ui_Button_Group2, 195);

    ui_Button_Radio2 = lv_imgbtn_create(ui_PERSONAL_CALL);
    lv_imgbtn_set_src(ui_Button_Radio2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radiopa_button_png, NULL);
    lv_obj_set_width(ui_Button_Radio2, 80);
    lv_obj_set_height(ui_Button_Radio2, 120);
    lv_obj_set_x(ui_Button_Radio2, 712);
    lv_obj_set_y(ui_Button_Radio2, 320);

    ui_logo_Intercom2 = lv_img_create(ui_PERSONAL_CALL);
    lv_img_set_src(ui_logo_Intercom2, &ui_img_logo_navysis_png);
    lv_obj_set_width(ui_logo_Intercom2, LV_SIZE_CONTENT);   /// 613
    lv_obj_set_height(ui_logo_Intercom2, LV_SIZE_CONTENT);    /// 248
    lv_obj_set_align(ui_logo_Intercom2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_Intercom2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_Intercom2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_list_Personal_call = lv_img_create(ui_PERSONAL_CALL);
    lv_img_set_src(ui_list_Personal_call, &ui_img_list_personal_incall_png);
    lv_obj_set_width(ui_list_Personal_call, LV_SIZE_CONTENT);   /// 685
    lv_obj_set_height(ui_list_Personal_call, LV_SIZE_CONTENT);    /// 415
    lv_obj_set_x(ui_list_Personal_call, 7);
    lv_obj_set_y(ui_list_Personal_call, 57);
    lv_obj_add_flag(ui_list_Personal_call, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_list_Personal_call, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Kom_Anjungan_call = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_Kom_Anjungan_call, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_kom_anjgan_call_png, NULL);
    lv_obj_set_width(ui_Kom_Anjungan_call, 110);
    lv_obj_set_height(ui_Kom_Anjungan_call, 100);

    ui_Palaksan_Anjungan_call = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_Palaksan_Anjungan_call, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_palaksa_call_png, NULL);
    lv_obj_set_width(ui_Palaksan_Anjungan_call, 110);
    lv_obj_set_height(ui_Palaksan_Anjungan_call, 100);
    lv_obj_set_x(ui_Palaksan_Anjungan_call, 115);
    lv_obj_set_y(ui_Palaksan_Anjungan_call, 0);

    ui_CIC_ROOM_call = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_CIC_ROOM_call, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_cic_room_call_png, NULL);
    lv_obj_set_width(ui_CIC_ROOM_call, 110);
    lv_obj_set_height(ui_CIC_ROOM_call, 100);
    lv_obj_set_x(ui_CIC_ROOM_call, 230);
    lv_obj_set_y(ui_CIC_ROOM_call, 0);

    ui_ECR_KA_call = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_ECR_KA_call, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_ecr_ka_call_png, NULL);
    lv_obj_set_width(ui_ECR_KA_call, 110);
    lv_obj_set_height(ui_ECR_KA_call, 100);
    lv_obj_set_x(ui_ECR_KA_call, 345);
    lv_obj_set_y(ui_ECR_KA_call, 0);

    ui_ECR_KI_call = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_ECR_KI_call, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_ecr_ki_call_png, NULL);
    lv_obj_set_width(ui_ECR_KI_call, 110);
    lv_obj_set_height(ui_ECR_KI_call, 100);
    lv_obj_set_x(ui_ECR_KI_call, 460);
    lv_obj_set_y(ui_ECR_KI_call, 0);

    ui_empty_call1 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call1, 110);
    lv_obj_set_height(ui_empty_call1, 100);
    lv_obj_set_x(ui_empty_call1, 575);
    lv_obj_set_y(ui_empty_call1, 0);

    ui_empty_call2 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call2, 110);
    lv_obj_set_height(ui_empty_call2, 100);
    lv_obj_set_x(ui_empty_call2, 0);
    lv_obj_set_y(ui_empty_call2, 105);

    ui_empty_call3 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call3, 110);
    lv_obj_set_height(ui_empty_call3, 100);
    lv_obj_set_x(ui_empty_call3, 115);
    lv_obj_set_y(ui_empty_call3, 105);

    ui_empty_call4 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call4, 110);
    lv_obj_set_height(ui_empty_call4, 100);
    lv_obj_set_x(ui_empty_call4, 230);
    lv_obj_set_y(ui_empty_call4, 105);

    ui_empty_call5 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call5, 110);
    lv_obj_set_height(ui_empty_call5, 100);
    lv_obj_set_x(ui_empty_call5, 345);
    lv_obj_set_y(ui_empty_call5, 105);

    ui_empty_call6 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call6, 110);
    lv_obj_set_height(ui_empty_call6, 100);
    lv_obj_set_x(ui_empty_call6, 460);
    lv_obj_set_y(ui_empty_call6, 105);

    ui_empty_call7 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call7, 110);
    lv_obj_set_height(ui_empty_call7, 100);
    lv_obj_set_x(ui_empty_call7, 575);
    lv_obj_set_y(ui_empty_call7, 105);

    ui_empty_call8 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call8, 110);
    lv_obj_set_height(ui_empty_call8, 100);
    lv_obj_set_x(ui_empty_call8, 0);
    lv_obj_set_y(ui_empty_call8, 210);

    ui_empty_call9 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call9, 110);
    lv_obj_set_height(ui_empty_call9, 100);
    lv_obj_set_x(ui_empty_call9, 115);
    lv_obj_set_y(ui_empty_call9, 210);

    ui_empty_call10 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call10, 110);
    lv_obj_set_height(ui_empty_call10, 100);
    lv_obj_set_x(ui_empty_call10, 230);
    lv_obj_set_y(ui_empty_call10, 210);

    ui_empty_call11 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call11, 110);
    lv_obj_set_height(ui_empty_call11, 100);
    lv_obj_set_x(ui_empty_call11, 345);
    lv_obj_set_y(ui_empty_call11, 210);

    ui_empty_call12 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call12, 110);
    lv_obj_set_height(ui_empty_call12, 100);
    lv_obj_set_x(ui_empty_call12, 460);
    lv_obj_set_y(ui_empty_call12, 210);

    ui_empty_call13 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_call13, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_call13, 110);
    lv_obj_set_height(ui_empty_call13, 100);
    lv_obj_set_x(ui_empty_call13, 575);
    lv_obj_set_y(ui_empty_call13, 210);

    ui_empty_Incall14 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_Incall14, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_Incall14, 110);
    lv_obj_set_height(ui_empty_Incall14, 100);
    lv_obj_set_x(ui_empty_Incall14, 0);
    lv_obj_set_y(ui_empty_Incall14, 315);

    ui_empty_Incall15 = lv_imgbtn_create(ui_list_Personal_call);
    lv_imgbtn_set_src(ui_empty_Incall15, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_Incall15, 110);
    lv_obj_set_height(ui_empty_Incall15, 100);
    lv_obj_set_x(ui_empty_Incall15, 115);
    lv_obj_set_y(ui_empty_Incall15, 315);

}
