// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_PERSONAL_SELECT_screen_init(void)
{
    ui_PERSONAL_SELECT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PERSONAL_SELECT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PERSONAL_SELECT, lv_color_hex(0x1480BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERSONAL_SELECT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PERSONAL_SELECT, lv_color_hex(0x03303C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PERSONAL_SELECT, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_server_on1 = lv_imgbtn_create(ui_PERSONAL_SELECT);
    lv_imgbtn_set_src(ui_server_on1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lucide_server_png, NULL);
    lv_obj_set_height(ui_server_on1, 28);
    lv_obj_set_width(ui_server_on1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_server_on1, 20);
    lv_obj_set_y(ui_server_on1, 14);

    ui_Peta_FF1 = lv_label_create(ui_PERSONAL_SELECT);
    lv_obj_set_width(ui_Peta_FF1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peta_FF1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peta_FF1, 51);
    lv_obj_set_y(ui_Peta_FF1, 14);
    lv_label_set_text(ui_Peta_FF1, "PETA FF");
    lv_obj_set_style_text_color(ui_Peta_FF1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Peta_FF1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Peta_FF1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waktu1 = lv_label_create(ui_PERSONAL_SELECT);
    lv_obj_set_width(ui_Waktu1, 73);
    lv_obj_set_height(ui_Waktu1, 33);
    lv_obj_set_x(ui_Waktu1, 436);
    lv_obj_set_y(ui_Waktu1, 16);
    lv_label_set_text(ui_Waktu1, "08:00");
    lv_obj_set_style_text_color(ui_Waktu1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waktu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waktu1, &ui_font_waktu, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sound1 = lv_imgbtn_create(ui_PERSONAL_SELECT);
    lv_imgbtn_set_src(ui_Sound1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1559931635, NULL);
    lv_obj_set_width(ui_Sound1, 40);
    lv_obj_set_height(ui_Sound1, 40);
    lv_obj_set_x(ui_Sound1, 518);
    lv_obj_set_y(ui_Sound1, 8);

    ui_Brightness1 = lv_imgbtn_create(ui_PERSONAL_SELECT);
    lv_imgbtn_set_src(ui_Brightness1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_388315622, NULL);
    lv_obj_set_width(ui_Brightness1, 50);
    lv_obj_set_height(ui_Brightness1, 50);
    lv_obj_set_x(ui_Brightness1, 567);
    lv_obj_set_y(ui_Brightness1, 3);

    ui_Setting1 = lv_imgbtn_create(ui_PERSONAL_SELECT);
    lv_imgbtn_set_src(ui_Setting1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1200060910, NULL);
    lv_obj_set_width(ui_Setting1, 40);
    lv_obj_set_height(ui_Setting1, 39);
    lv_obj_set_x(ui_Setting1, 626);
    lv_obj_set_y(ui_Setting1, 8);

    ui_Personal_Select = lv_imgbtn_create(ui_PERSONAL_SELECT);
    lv_imgbtn_set_src(ui_Personal_Select, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_personal_buttonn_png, NULL);
    lv_obj_set_width(ui_Personal_Select, 80);
    lv_obj_set_height(ui_Personal_Select, 100);
    lv_obj_set_x(ui_Personal_Select, 711);
    lv_obj_set_y(ui_Personal_Select, 65);

    ui_Personal_Group_Select = lv_imgbtn_create(ui_PERSONAL_SELECT);
    lv_imgbtn_set_src(ui_Personal_Group_Select, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_button_png, NULL);
    lv_obj_set_width(ui_Personal_Group_Select, 80);
    lv_obj_set_height(ui_Personal_Group_Select, 100);
    lv_obj_set_x(ui_Personal_Group_Select, 711);
    lv_obj_set_y(ui_Personal_Group_Select, 195);

    ui_Personal_Radio_Select = lv_imgbtn_create(ui_PERSONAL_SELECT);
    lv_imgbtn_set_src(ui_Personal_Radio_Select, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radiopa_button_png, NULL);
    lv_obj_set_width(ui_Personal_Radio_Select, 80);
    lv_obj_set_height(ui_Personal_Radio_Select, 120);
    lv_obj_set_x(ui_Personal_Radio_Select, 712);
    lv_obj_set_y(ui_Personal_Radio_Select, 320);

    ui_logo_Intercom1 = lv_img_create(ui_PERSONAL_SELECT);
    lv_img_set_src(ui_logo_Intercom1, &ui_img_logo_navysis_png);
    lv_obj_set_width(ui_logo_Intercom1, LV_SIZE_CONTENT);   /// 613
    lv_obj_set_height(ui_logo_Intercom1, LV_SIZE_CONTENT);    /// 248
    lv_obj_set_align(ui_logo_Intercom1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_Intercom1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_Intercom1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_list_Personal_select = lv_img_create(ui_PERSONAL_SELECT);
    lv_img_set_src(ui_list_Personal_select, &ui_img_list_personal_incall_png);
    lv_obj_set_width(ui_list_Personal_select, LV_SIZE_CONTENT);   /// 685
    lv_obj_set_height(ui_list_Personal_select, LV_SIZE_CONTENT);    /// 415
    lv_obj_set_x(ui_list_Personal_select, 7);
    lv_obj_set_y(ui_list_Personal_select, 57);
    lv_obj_add_flag(ui_list_Personal_select, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_list_Personal_select, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Kom_Anjungan_select = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_Kom_Anjungan_select, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_komandan_anjungan_home_png, NULL);
    lv_obj_set_width(ui_Kom_Anjungan_select, 110);
    lv_obj_set_height(ui_Kom_Anjungan_select, 100);

    ui_Palaksan_Anjungan_select = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_Palaksan_Anjungan_select, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_palaksa_anjgan_home_png,
                      NULL);
    lv_obj_set_width(ui_Palaksan_Anjungan_select, 110);
    lv_obj_set_height(ui_Palaksan_Anjungan_select, 100);
    lv_obj_set_x(ui_Palaksan_Anjungan_select, 115);
    lv_obj_set_y(ui_Palaksan_Anjungan_select, 0);

    ui_CIC_ROOM__select = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_CIC_ROOM__select, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_cic_room_home_png, NULL);
    lv_obj_set_width(ui_CIC_ROOM__select, 110);
    lv_obj_set_height(ui_CIC_ROOM__select, 100);
    lv_obj_set_x(ui_CIC_ROOM__select, 230);
    lv_obj_set_y(ui_CIC_ROOM__select, 0);

    ui_ECR_KA__select = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_ECR_KA__select, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_r_ecr_ka_home_png, NULL);
    lv_obj_set_width(ui_ECR_KA__select, 110);
    lv_obj_set_height(ui_ECR_KA__select, 100);
    lv_obj_set_x(ui_ECR_KA__select, 345);
    lv_obj_set_y(ui_ECR_KA__select, 0);

    ui_ECR_KI__select = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_ECR_KI__select, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_r_ecr_ki_home_png, NULL);
    lv_obj_set_width(ui_ECR_KI__select, 110);
    lv_obj_set_height(ui_ECR_KI__select, 100);
    lv_obj_set_x(ui_ECR_KI__select, 460);
    lv_obj_set_y(ui_ECR_KI__select, 0);

    ui_empty_1 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty_1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty_1, 110);
    lv_obj_set_height(ui_empty_1, 100);
    lv_obj_set_x(ui_empty_1, 575);
    lv_obj_set_y(ui_empty_1, 0);

    ui_empty2 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty2, 110);
    lv_obj_set_height(ui_empty2, 100);
    lv_obj_set_x(ui_empty2, 0);
    lv_obj_set_y(ui_empty2, 105);

    ui_empty3 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty3, 110);
    lv_obj_set_height(ui_empty3, 100);
    lv_obj_set_x(ui_empty3, 115);
    lv_obj_set_y(ui_empty3, 105);

    ui_empty4 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty4, 110);
    lv_obj_set_height(ui_empty4, 100);
    lv_obj_set_x(ui_empty4, 230);
    lv_obj_set_y(ui_empty4, 105);

    ui_empty5 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty5, 110);
    lv_obj_set_height(ui_empty5, 100);
    lv_obj_set_x(ui_empty5, 345);
    lv_obj_set_y(ui_empty5, 105);

    ui_empty6 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty6, 110);
    lv_obj_set_height(ui_empty6, 100);
    lv_obj_set_x(ui_empty6, 460);
    lv_obj_set_y(ui_empty6, 105);

    ui_empty7 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty7, 110);
    lv_obj_set_height(ui_empty7, 100);
    lv_obj_set_x(ui_empty7, 575);
    lv_obj_set_y(ui_empty7, 105);

    ui_empty8 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty8, 110);
    lv_obj_set_height(ui_empty8, 100);
    lv_obj_set_x(ui_empty8, 0);
    lv_obj_set_y(ui_empty8, 210);

    ui_empty9 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty9, 110);
    lv_obj_set_height(ui_empty9, 100);
    lv_obj_set_x(ui_empty9, 115);
    lv_obj_set_y(ui_empty9, 210);

    ui_empty10 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty10, 110);
    lv_obj_set_height(ui_empty10, 100);
    lv_obj_set_x(ui_empty10, 230);
    lv_obj_set_y(ui_empty10, 210);

    ui_empty11 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty11, 110);
    lv_obj_set_height(ui_empty11, 100);
    lv_obj_set_x(ui_empty11, 345);
    lv_obj_set_y(ui_empty11, 210);

    ui_empty12 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty12, 110);
    lv_obj_set_height(ui_empty12, 100);
    lv_obj_set_x(ui_empty12, 460);
    lv_obj_set_y(ui_empty12, 210);

    ui_empty13 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty13, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty13, 110);
    lv_obj_set_height(ui_empty13, 100);
    lv_obj_set_x(ui_empty13, 575);
    lv_obj_set_y(ui_empty13, 210);

    ui_empty14 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty14, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty14, 110);
    lv_obj_set_height(ui_empty14, 100);
    lv_obj_set_x(ui_empty14, 0);
    lv_obj_set_y(ui_empty14, 315);

    ui_empty15 = lv_imgbtn_create(ui_list_Personal_select);
    lv_imgbtn_set_src(ui_empty15, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty15, 110);
    lv_obj_set_height(ui_empty15, 100);
    lv_obj_set_x(ui_empty15, 115);
    lv_obj_set_y(ui_empty15, 315);

    lv_obj_add_event_cb(ui_Personal_Select, ui_event_Personal_Select, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_Personal_Group_Select, ui_event_Personal_Group_Select, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_Personal_Radio_Select, ui_event_Personal_Radio_Select, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Sound1, ui_event_Sound1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Brightness1, ui_event_Brightness1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting1, ui_event_Setting1, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Kom_Anjungan_select,ui_event_Kom_Anjungan_select_clicked_callback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Palaksan_Anjungan_select, ui_event_Palaksan_Anjungan_select_clicked_callback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CIC_ROOM__select, ui_event_CIC_ROOM_select_clicked_callback ,LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ECR_KA__select, ui_event_ECR_KA_select_clicked_callback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ECR_KI__select, ui_event_ECR_KI_select_clicked_callback, LV_EVENT_ALL, NULL);



}
