// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_RADIO_SELECT_screen_init(void)
{
    ui_RADIO_SELECT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RADIO_SELECT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RADIO_SELECT, lv_color_hex(0x1480BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RADIO_SELECT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RADIO_SELECT, lv_color_hex(0x03303C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RADIO_SELECT, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_server_on5 = lv_imgbtn_create(ui_RADIO_SELECT);
    lv_imgbtn_set_src(ui_server_on5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lucide_server_png, NULL);
    lv_obj_set_height(ui_server_on5, 28);
    lv_obj_set_width(ui_server_on5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_server_on5, 20);
    lv_obj_set_y(ui_server_on5, 14);

    ui_Peta_FF5 = lv_label_create(ui_RADIO_SELECT);
    lv_obj_set_width(ui_Peta_FF5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peta_FF5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peta_FF5, 51);
    lv_obj_set_y(ui_Peta_FF5, 14);
    lv_label_set_text(ui_Peta_FF5, "PETA FF");
    lv_obj_set_style_text_color(ui_Peta_FF5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Peta_FF5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Peta_FF5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waktu5 = lv_label_create(ui_RADIO_SELECT);
    lv_obj_set_width(ui_Waktu5, 73);
    lv_obj_set_height(ui_Waktu5, 33);
    lv_obj_set_x(ui_Waktu5, 436);
    lv_obj_set_y(ui_Waktu5, 16);
    lv_label_set_text(ui_Waktu5, "08:00");
    lv_obj_set_style_text_color(ui_Waktu5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waktu5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waktu5, &ui_font_waktu, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sound5 = lv_imgbtn_create(ui_RADIO_SELECT);
    lv_imgbtn_set_src(ui_Sound5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1559931635, NULL);
    lv_obj_set_width(ui_Sound5, 40);
    lv_obj_set_height(ui_Sound5, 40);
    lv_obj_set_x(ui_Sound5, 518);
    lv_obj_set_y(ui_Sound5, 8);

    ui_Brightness5 = lv_imgbtn_create(ui_RADIO_SELECT);
    lv_imgbtn_set_src(ui_Brightness5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_388315622, NULL);
    lv_obj_set_width(ui_Brightness5, 50);
    lv_obj_set_height(ui_Brightness5, 50);
    lv_obj_set_x(ui_Brightness5, 567);
    lv_obj_set_y(ui_Brightness5, 3);

    ui_Setting5 = lv_imgbtn_create(ui_RADIO_SELECT);
    lv_imgbtn_set_src(ui_Setting5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1200060910, NULL);
    lv_obj_set_width(ui_Setting5, 40);
    lv_obj_set_height(ui_Setting5, 39);
    lv_obj_set_x(ui_Setting5, 626);
    lv_obj_set_y(ui_Setting5, 8);

    ui_Personal_radio = lv_imgbtn_create(ui_RADIO_SELECT);
    lv_imgbtn_set_src(ui_Personal_radio, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_personal_button_png, NULL);
    lv_obj_set_width(ui_Personal_radio, 80);
    lv_obj_set_height(ui_Personal_radio, 100);
    lv_obj_set_x(ui_Personal_radio, 711);
    lv_obj_set_y(ui_Personal_radio, 65);

    ui_Group_radio = lv_imgbtn_create(ui_RADIO_SELECT);
    lv_imgbtn_set_src(ui_Group_radio, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_button_png, NULL);
    lv_obj_set_width(ui_Group_radio, 80);
    lv_obj_set_height(ui_Group_radio, 100);
    lv_obj_set_x(ui_Group_radio, 711);
    lv_obj_set_y(ui_Group_radio, 195);

    ui_Radiopa_select = lv_imgbtn_create(ui_RADIO_SELECT);
    lv_imgbtn_set_src(ui_Radiopa_select, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_pa_button_png, NULL);
    lv_obj_set_width(ui_Radiopa_select, 80);
    lv_obj_set_height(ui_Radiopa_select, 120);
    lv_obj_set_x(ui_Radiopa_select, 712);
    lv_obj_set_y(ui_Radiopa_select, 320);

    ui_logo_intercom_5 = lv_img_create(ui_RADIO_SELECT);
    lv_img_set_src(ui_logo_intercom_5, &ui_img_logo_navysis_png);
    lv_obj_set_width(ui_logo_intercom_5, LV_SIZE_CONTENT);   /// 613
    lv_obj_set_height(ui_logo_intercom_5, LV_SIZE_CONTENT);    /// 248
    lv_obj_set_align(ui_logo_intercom_5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_intercom_5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_intercom_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_list_personal_radio = lv_img_create(ui_RADIO_SELECT);
    lv_img_set_src(ui_list_personal_radio, &ui_img_list_group_png);
    lv_obj_set_width(ui_list_personal_radio, LV_SIZE_CONTENT);   /// 685
    lv_obj_set_height(ui_list_personal_radio, LV_SIZE_CONTENT);    /// 415
    lv_obj_set_x(ui_list_personal_radio, 7);
    lv_obj_set_y(ui_list_personal_radio, 57);
    lv_obj_add_flag(ui_list_personal_radio, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_list_personal_radio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_radio1 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radio1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_operatif_incall1_png, NULL);
    lv_obj_set_width(ui_radio1, 110);
    lv_obj_set_height(ui_radio1, 100);

    ui_radio2 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radio2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_operatif_incall2_png, NULL);
    lv_obj_set_width(ui_radio2, 110);
    lv_obj_set_height(ui_radio2, 100);
    lv_obj_set_x(ui_radio2, 115);
    lv_obj_set_y(ui_radio2, 0);

    ui_radio3 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radio3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_operatif_incall3_png, NULL);
    lv_obj_set_width(ui_radio3, 110);
    lv_obj_set_height(ui_radio3, 100);
    lv_obj_set_x(ui_radio3, 230);
    lv_obj_set_y(ui_radio3, 0);

    ui_radio4 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radio4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_operatif_incall4_png, NULL);
    lv_obj_set_width(ui_radio4, 110);
    lv_obj_set_height(ui_radio4, 100);
    lv_obj_set_x(ui_radio4, 345);
    lv_obj_set_y(ui_radio4, 0);

    ui_radio5 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radio5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_operatif_incall5_png, NULL);
    lv_obj_set_width(ui_radio5, 110);
    lv_obj_set_height(ui_radio5, 100);
    lv_obj_set_x(ui_radio5, 460);
    lv_obj_set_y(ui_radio5, 0);

    ui_radio6 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radio6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_operatif_incall5_png, NULL);
    lv_obj_set_width(ui_radio6, 110);
    lv_obj_set_height(ui_radio6, 100);
    lv_obj_set_x(ui_radio6, 575);
    lv_obj_set_y(ui_radio6, 0);

    ui_radio7 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radio7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_operatif_incall7_png, NULL);
    lv_obj_set_width(ui_radio7, 110);
    lv_obj_set_height(ui_radio7, 100);
    lv_obj_set_x(ui_radio7, 0);
    lv_obj_set_y(ui_radio7, 105);

    ui_radio8 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radio8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_operatif_incall8_png, NULL);
    lv_obj_set_width(ui_radio8, 110);
    lv_obj_set_height(ui_radio8, 100);
    lv_obj_set_x(ui_radio8, 115);
    lv_obj_set_y(ui_radio8, 105);

    ui_radio9 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radio9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_operatif_incall9_png, NULL);
    lv_obj_set_width(ui_radio9, 110);
    lv_obj_set_height(ui_radio9, 100);
    lv_obj_set_x(ui_radio9, 230);
    lv_obj_set_y(ui_radio9, 105);

    ui_radio10 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radio10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_operatif_incall10_png, NULL);
    lv_obj_set_width(ui_radio10, 110);
    lv_obj_set_height(ui_radio10, 100);
    lv_obj_set_x(ui_radio10, 345);
    lv_obj_set_y(ui_radio10, 105);

    ui_radioempty11 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radioempty11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_5_png, NULL);
    lv_obj_set_width(ui_radioempty11, 110);
    lv_obj_set_height(ui_radioempty11, 100);
    lv_obj_set_x(ui_radioempty11, 460);
    lv_obj_set_y(ui_radioempty11, 105);

    ui_radioempty12 = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_radioempty12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_calling_6__png, NULL);
    lv_obj_set_width(ui_radioempty12, 110);
    lv_obj_set_height(ui_radioempty12, 100);
    lv_obj_set_x(ui_radioempty12, 575);
    lv_obj_set_y(ui_radioempty12, 105);

    ui_mainbroadcast = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_mainbroadcast, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_mainbroadcest_incall17_png, NULL);
    lv_obj_set_width(ui_mainbroadcast, 110);
    lv_obj_set_height(ui_mainbroadcast, 100);
    lv_obj_set_x(ui_mainbroadcast, 0);
    lv_obj_set_y(ui_mainbroadcast, 210);

    ui_operatif = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_operatif, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_frame_12_png, NULL);
    lv_obj_set_width(ui_operatif, 110);
    lv_obj_set_height(ui_operatif, 100);
    lv_obj_set_x(ui_operatif, 115);
    lv_obj_set_y(ui_operatif, 210);

    ui_darurat = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_darurat, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_frame_13_png, NULL);
    lv_obj_set_width(ui_darurat, 110);
    lv_obj_set_height(ui_darurat, 100);
    lv_obj_set_x(ui_darurat, 230);
    lv_obj_set_y(ui_darurat, 210);

    ui_kebakaran = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_kebakaran, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_kebakaran_incall14_png, NULL);
    lv_obj_set_width(ui_kebakaran, 110);
    lv_obj_set_height(ui_kebakaran, 100);
    lv_obj_set_x(ui_kebakaran, 345);
    lv_obj_set_y(ui_kebakaran, 210);

    ui_khusus = lv_imgbtn_create(ui_list_personal_radio);
    lv_imgbtn_set_src(ui_khusus, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radio_khusus_incall15_png, NULL);
    lv_obj_set_width(ui_khusus, 110);
    lv_obj_set_height(ui_khusus, 100);
    lv_obj_set_x(ui_khusus, 460);
    lv_obj_set_y(ui_khusus, 210);

}
