// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_Start_Up_screen_init(void)
{
    ui_Start_Up = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Start_Up, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Start_Up, lv_color_hex(0x234A81), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Start_Up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo_Interkom = lv_img_create(ui_Start_Up);
    lv_img_set_src(ui_Logo_Interkom, &ui_img_icon_png);
    lv_obj_set_width(ui_Logo_Interkom, 630);
    lv_obj_set_height(ui_Logo_Interkom, 239);
    lv_obj_set_x(ui_Logo_Interkom, 8);
    lv_obj_set_y(ui_Logo_Interkom, -29);
    lv_obj_set_align(ui_Logo_Interkom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo_Interkom, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo_Interkom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loader = lv_spinner_create(ui_Start_Up, 1000, 90);
    lv_obj_set_width(ui_loader, 40);
    lv_obj_set_height(ui_loader, 40);
    lv_obj_set_x(ui_loader, 381);
    lv_obj_set_y(ui_loader, 315);
    lv_obj_clear_flag(ui_loader, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_loader, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_loader, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_initializations = lv_label_create(ui_Start_Up);
    lv_obj_set_width(ui_initializations, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_initializations, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_initializations, 7);
    lv_obj_set_y(ui_initializations, 135);
    lv_obj_set_align(ui_initializations, LV_ALIGN_CENTER);
    lv_label_set_text(ui_initializations, "Initializations ....");
    lv_obj_set_style_text_color(ui_initializations, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_initializations, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
