// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_SETTING_screen_init(void)
{
    ui_SETTING = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SETTING, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SETTING, lv_color_hex(0x1480BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SETTING, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SETTING, lv_color_hex(0x03303C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SETTING, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_server_on8 = lv_imgbtn_create(ui_SETTING);
    lv_imgbtn_set_src(ui_server_on8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lucide_server_png, NULL);
    lv_obj_set_height(ui_server_on8, 28);
    lv_obj_set_width(ui_server_on8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_server_on8, 20);
    lv_obj_set_y(ui_server_on8, 14);

    ui_Peta_FF8 = lv_label_create(ui_SETTING);
    lv_obj_set_width(ui_Peta_FF8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peta_FF8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peta_FF8, 51);
    lv_obj_set_y(ui_Peta_FF8, 14);
    lv_label_set_text(ui_Peta_FF8, "PETA FF");
    lv_obj_set_style_text_color(ui_Peta_FF8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Peta_FF8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Peta_FF8, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waktu8 = lv_label_create(ui_SETTING);
    lv_obj_set_width(ui_Waktu8, 73);
    lv_obj_set_height(ui_Waktu8, 33);
    lv_obj_set_x(ui_Waktu8, 436);
    lv_obj_set_y(ui_Waktu8, 16);
    lv_label_set_text(ui_Waktu8, "08:00");
    lv_obj_set_style_text_color(ui_Waktu8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waktu8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waktu8, &ui_font_waktu, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sound8 = lv_imgbtn_create(ui_SETTING);
    lv_imgbtn_set_src(ui_Sound8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1559931635, NULL);
    lv_obj_set_width(ui_Sound8, 40);
    lv_obj_set_height(ui_Sound8, 40);
    lv_obj_set_x(ui_Sound8, 518);
    lv_obj_set_y(ui_Sound8, 8);

    ui_Brightness8 = lv_imgbtn_create(ui_SETTING);
    lv_imgbtn_set_src(ui_Brightness8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_388315622, NULL);
    lv_obj_set_width(ui_Brightness8, 50);
    lv_obj_set_height(ui_Brightness8, 50);
    lv_obj_set_x(ui_Brightness8, 567);
    lv_obj_set_y(ui_Brightness8, 3);

    ui_Setting8 = lv_imgbtn_create(ui_SETTING);
    lv_imgbtn_set_src(ui_Setting8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_111514558, NULL);
    lv_obj_set_width(ui_Setting8, 40);
    lv_obj_set_height(ui_Setting8, 39);
    lv_obj_set_x(ui_Setting8, 626);
    lv_obj_set_y(ui_Setting8, 8);

    ui_Personal_setting8 = lv_imgbtn_create(ui_SETTING);
    lv_imgbtn_set_src(ui_Personal_setting8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_personal_button_png, NULL);
    lv_obj_set_width(ui_Personal_setting8, 80);
    lv_obj_set_height(ui_Personal_setting8, 100);
    lv_obj_set_x(ui_Personal_setting8, 711);
    lv_obj_set_y(ui_Personal_setting8, 65);

    ui_Group_setting8 = lv_imgbtn_create(ui_SETTING);
    lv_imgbtn_set_src(ui_Group_setting8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_button_png, NULL);
    lv_obj_set_width(ui_Group_setting8, 80);
    lv_obj_set_height(ui_Group_setting8, 100);
    lv_obj_set_x(ui_Group_setting8, 711);
    lv_obj_set_y(ui_Group_setting8, 195);

    ui_radio_setting8 = lv_imgbtn_create(ui_SETTING);
    lv_imgbtn_set_src(ui_radio_setting8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radiopa_button_png, NULL);
    lv_obj_set_width(ui_radio_setting8, 80);
    lv_obj_set_height(ui_radio_setting8, 120);
    lv_obj_set_x(ui_radio_setting8, 712);
    lv_obj_set_y(ui_radio_setting8, 320);

    ui_logo_intercom8 = lv_img_create(ui_SETTING);
    lv_img_set_src(ui_logo_intercom8, &ui_img_logo_navysis_png);
    lv_obj_set_width(ui_logo_intercom8, LV_SIZE_CONTENT);   /// 613
    lv_obj_set_height(ui_logo_intercom8, LV_SIZE_CONTENT);    /// 248
    lv_obj_set_align(ui_logo_intercom8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_intercom8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_intercom8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_popup_setting8 = lv_img_create(ui_SETTING);
    lv_img_set_src(ui_popup_setting8, &ui_img_popup_set_png);
    lv_obj_set_width(ui_popup_setting8, LV_SIZE_CONTENT);   /// 685
    lv_obj_set_height(ui_popup_setting8, LV_SIZE_CONTENT);    /// 405
    lv_obj_set_x(ui_popup_setting8, 10);
    lv_obj_set_y(ui_popup_setting8, 64);
    lv_obj_add_flag(ui_popup_setting8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_popup_setting8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Setting8 = lv_label_create(ui_popup_setting8);
    lv_obj_set_width(ui_Label_Setting8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Setting8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Setting8, 20);
    lv_obj_set_y(ui_Label_Setting8, 22);
    lv_label_set_text(ui_Label_Setting8, "SETTING");
    lv_obj_set_style_text_color(ui_Label_Setting8, lv_color_hex(0x234A81), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Setting8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Setting8, &ui_font_pabx, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Performance = lv_imgbtn_create(ui_popup_setting8);
    lv_imgbtn_set_src(ui_Button_Performance, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_performance_png, NULL);
    lv_obj_set_width(ui_Button_Performance, 100);
    lv_obj_set_height(ui_Button_Performance, 30);
    lv_obj_set_x(ui_Button_Performance, 23);
    lv_obj_set_y(ui_Button_Performance, 54);

    ui_Button_Selftest = lv_imgbtn_create(ui_popup_setting8);
    lv_imgbtn_set_src(ui_Button_Selftest, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1693904590, NULL);
    lv_obj_set_width(ui_Button_Selftest, 100);
    lv_obj_set_height(ui_Button_Selftest, 30);
    lv_obj_set_x(ui_Button_Selftest, 123);
    lv_obj_set_y(ui_Button_Selftest, 54);

    ui_Button_About = lv_imgbtn_create(ui_popup_setting8);
    lv_imgbtn_set_src(ui_Button_About, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_55024288, NULL);
    lv_obj_set_width(ui_Button_About, 100);
    lv_obj_set_height(ui_Button_About, 30);
    lv_obj_set_x(ui_Button_About, 223);
    lv_obj_set_y(ui_Button_About, 54);

    ui_Label_CPU = lv_label_create(ui_popup_setting8);
    lv_obj_set_width(ui_Label_CPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_CPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_CPU, 23);
    lv_obj_set_y(ui_Label_CPU, 104);
    lv_label_set_text(ui_Label_CPU, "CPU");
    lv_obj_set_style_text_font(ui_Label_CPU, &ui_font_CPU, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_value_CPU = lv_label_create(ui_popup_setting8);
    lv_obj_set_width(ui_value_CPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value_CPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value_CPU, 30);
    lv_obj_set_y(ui_value_CPU, 131);
    lv_label_set_text(ui_value_CPU, "10% 0.88 MHz");
    lv_obj_set_style_text_font(ui_value_CPU, &ui_font_MHz, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Memory = lv_label_create(ui_popup_setting8);
    lv_obj_set_width(ui_Label_Memory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Memory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Memory, 270);
    lv_obj_set_y(ui_Label_Memory, 104);
    lv_label_set_text(ui_Label_Memory, "Memory");
    lv_obj_set_style_text_font(ui_Label_Memory, &ui_font_CPU, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_value_Memory = lv_label_create(ui_popup_setting8);
    lv_obj_set_width(ui_value_Memory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value_Memory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value_Memory, 287);
    lv_obj_set_y(ui_value_Memory, 131);
    lv_label_set_text(ui_value_Memory, "355/865 MB (45%)");
    lv_obj_set_style_text_font(ui_value_Memory, &ui_font_MHz, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_grafik_CPU = lv_img_create(ui_popup_setting8);
    lv_img_set_src(ui_grafik_CPU, &ui_img_frame_grafik_cpu_png);
    lv_obj_set_width(ui_grafik_CPU, LV_SIZE_CONTENT);   /// 175
    lv_obj_set_height(ui_grafik_CPU, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_x(ui_grafik_CPU, 23);
    lv_obj_set_y(ui_grafik_CPU, 160);
    lv_obj_add_flag(ui_grafik_CPU, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_grafik_CPU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Grafik_Memory = lv_img_create(ui_popup_setting8);
    lv_img_set_src(ui_Grafik_Memory, &ui_img_frame_grafik_memory_png);
    lv_obj_set_width(ui_Grafik_Memory, LV_SIZE_CONTENT);   /// 177
    lv_obj_set_height(ui_Grafik_Memory, LV_SIZE_CONTENT);    /// 121
    lv_obj_set_x(ui_Grafik_Memory, 270);
    lv_obj_set_y(ui_Grafik_Memory, 160);
    lv_obj_add_flag(ui_Grafik_Memory, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Grafik_Memory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Setting8, ui_event_Setting8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Selftest, ui_event_Button_Selftest, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_About, ui_event_Button_About, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Performance, ui_event_Button_Performance, LV_EVENT_ALL, NULL);
}