// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_SELFTEST_screen_init(void)
{
    ui_SELFTEST = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SELFTEST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SELFTEST, lv_color_hex(0x1480BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SELFTEST, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SELFTEST, lv_color_hex(0x03303C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SELFTEST, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_server_on9 = lv_imgbtn_create(ui_SELFTEST);
    lv_imgbtn_set_src(ui_server_on9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lucide_server_png, NULL);
    lv_obj_set_height(ui_server_on9, 28);
    lv_obj_set_width(ui_server_on9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_server_on9, 20);
    lv_obj_set_y(ui_server_on9, 14);

    ui_Peta_FF9 = lv_label_create(ui_SELFTEST);
    lv_obj_set_width(ui_Peta_FF9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peta_FF9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peta_FF9, 51);
    lv_obj_set_y(ui_Peta_FF9, 14);
    lv_label_set_text(ui_Peta_FF9, "PETA FF");
    lv_obj_set_style_text_color(ui_Peta_FF9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Peta_FF9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Peta_FF9, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waktu9 = lv_label_create(ui_SELFTEST);
    lv_obj_set_width(ui_Waktu9, 73);
    lv_obj_set_height(ui_Waktu9, 33);
    lv_obj_set_x(ui_Waktu9, 436);
    lv_obj_set_y(ui_Waktu9, 16);
    lv_label_set_text(ui_Waktu9, "08:00");
    lv_obj_set_style_text_color(ui_Waktu9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waktu9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waktu9, &ui_font_waktu, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sound9 = lv_imgbtn_create(ui_SELFTEST);
    lv_imgbtn_set_src(ui_Sound9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1559931635, NULL);
    lv_obj_set_width(ui_Sound9, 40);
    lv_obj_set_height(ui_Sound9, 40);
    lv_obj_set_x(ui_Sound9, 518);
    lv_obj_set_y(ui_Sound9, 8);

    ui_Brightness9 = lv_imgbtn_create(ui_SELFTEST);
    lv_imgbtn_set_src(ui_Brightness9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_388315622, NULL);
    lv_obj_set_width(ui_Brightness9, 50);
    lv_obj_set_height(ui_Brightness9, 50);
    lv_obj_set_x(ui_Brightness9, 567);
    lv_obj_set_y(ui_Brightness9, 3);

    ui_Setting9 = lv_imgbtn_create(ui_SELFTEST);
    lv_imgbtn_set_src(ui_Setting9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_111514558, NULL);
    lv_obj_set_width(ui_Setting9, 40);
    lv_obj_set_height(ui_Setting9, 39);
    lv_obj_set_x(ui_Setting9, 626);
    lv_obj_set_y(ui_Setting9, 8);

    ui_Personal_setting9 = lv_imgbtn_create(ui_SELFTEST);
    lv_imgbtn_set_src(ui_Personal_setting9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_personal_button_png, NULL);
    lv_obj_set_width(ui_Personal_setting9, 80);
    lv_obj_set_height(ui_Personal_setting9, 100);
    lv_obj_set_x(ui_Personal_setting9, 711);
    lv_obj_set_y(ui_Personal_setting9, 65);

    ui_Group_setting9 = lv_imgbtn_create(ui_SELFTEST);
    lv_imgbtn_set_src(ui_Group_setting9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_button_png, NULL);
    lv_obj_set_width(ui_Group_setting9, 80);
    lv_obj_set_height(ui_Group_setting9, 100);
    lv_obj_set_x(ui_Group_setting9, 711);
    lv_obj_set_y(ui_Group_setting9, 195);

    ui_radio_setting9 = lv_imgbtn_create(ui_SELFTEST);
    lv_imgbtn_set_src(ui_radio_setting9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radiopa_button_png, NULL);
    lv_obj_set_width(ui_radio_setting9, 80);
    lv_obj_set_height(ui_radio_setting9, 120);
    lv_obj_set_x(ui_radio_setting9, 712);
    lv_obj_set_y(ui_radio_setting9, 320);

    ui_logo_intercom9 = lv_img_create(ui_SELFTEST);
    lv_img_set_src(ui_logo_intercom9, &ui_img_logo_navysis_png);
    lv_obj_set_width(ui_logo_intercom9, LV_SIZE_CONTENT);   /// 613
    lv_obj_set_height(ui_logo_intercom9, LV_SIZE_CONTENT);    /// 248
    lv_obj_set_align(ui_logo_intercom9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_intercom9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_intercom9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_popup_setting9 = lv_img_create(ui_SELFTEST);
    lv_img_set_src(ui_popup_setting9, &ui_img_popup_set_png);
    lv_obj_set_width(ui_popup_setting9, LV_SIZE_CONTENT);   /// 685
    lv_obj_set_height(ui_popup_setting9, LV_SIZE_CONTENT);    /// 405
    lv_obj_set_x(ui_popup_setting9, 10);
    lv_obj_set_y(ui_popup_setting9, 64);
    lv_obj_add_flag(ui_popup_setting9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_popup_setting9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Setting9 = lv_label_create(ui_popup_setting9);
    lv_obj_set_width(ui_Label_Setting9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Setting9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Setting9, 20);
    lv_obj_set_y(ui_Label_Setting9, 22);
    lv_label_set_text(ui_Label_Setting9, "SETTING");
    lv_obj_set_style_text_color(ui_Label_Setting9, lv_color_hex(0x234A81), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Setting9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Setting9, &ui_font_pabx, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Performance1 = lv_imgbtn_create(ui_popup_setting9);
    lv_imgbtn_set_src(ui_Button_Performance1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_430847109, NULL);
    lv_obj_set_width(ui_Button_Performance1, 100);
    lv_obj_set_height(ui_Button_Performance1, 30);
    lv_obj_set_x(ui_Button_Performance1, 23);
    lv_obj_set_y(ui_Button_Performance1, 54);

    ui_Button_Selftest1 = lv_imgbtn_create(ui_popup_setting9);
    lv_imgbtn_set_src(ui_Button_Selftest1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1930036399, NULL);
    lv_obj_set_width(ui_Button_Selftest1, 100);
    lv_obj_set_height(ui_Button_Selftest1, 30);
    lv_obj_set_x(ui_Button_Selftest1, 123);
    lv_obj_set_y(ui_Button_Selftest1, 54);

    ui_Button_About1 = lv_imgbtn_create(ui_popup_setting9);
    lv_imgbtn_set_src(ui_Button_About1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_55024288, NULL);
    lv_obj_set_width(ui_Button_About1, 100);
    lv_obj_set_height(ui_Button_About1, 30);
    lv_obj_set_x(ui_Button_About1, 223);
    lv_obj_set_y(ui_Button_About1, 54);

    ui_Label_Selftest = lv_label_create(ui_popup_setting9);
    lv_obj_set_width(ui_Label_Selftest, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Selftest, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Selftest, 33);
    lv_obj_set_y(ui_Label_Selftest, 98);
    lv_label_set_text(ui_Label_Selftest, "Future page on proccess design and testing");
    lv_obj_set_style_text_font(ui_Label_Selftest, &ui_font_MHz, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button_Selftest1, ui_event_Button_Selftest1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Performance1, ui_event_Button_Performance1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_About1, ui_event_Button_About1, LV_EVENT_ALL, NULL);
}
