// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_VOLUME_screen_init(void)
{
    ui_VOLUME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_VOLUME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VOLUME, lv_color_hex(0x1480BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VOLUME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_VOLUME, lv_color_hex(0x03303C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_VOLUME, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_server_on6 = lv_imgbtn_create(ui_VOLUME);
    lv_imgbtn_set_src(ui_server_on6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lucide_server_png, NULL);
    lv_obj_set_height(ui_server_on6, 28);
    lv_obj_set_width(ui_server_on6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_server_on6, 20);
    lv_obj_set_y(ui_server_on6, 14);

    ui_Peta_FF6 = lv_label_create(ui_VOLUME);
    lv_obj_set_width(ui_Peta_FF6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peta_FF6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peta_FF6, 51);
    lv_obj_set_y(ui_Peta_FF6, 14);
    lv_label_set_text(ui_Peta_FF6, "PETA FF");
    lv_obj_set_style_text_color(ui_Peta_FF6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Peta_FF6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Peta_FF6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waktu6 = lv_label_create(ui_VOLUME);
    lv_obj_set_width(ui_Waktu6, 73);
    lv_obj_set_height(ui_Waktu6, 33);
    lv_obj_set_x(ui_Waktu6, 436);
    lv_obj_set_y(ui_Waktu6, 16);
    lv_label_set_text(ui_Waktu6, "08:00");
    lv_obj_set_style_text_color(ui_Waktu6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waktu6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waktu6, &ui_font_waktu, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sound6 = lv_imgbtn_create(ui_VOLUME);
    lv_imgbtn_set_src(ui_Sound6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_824966301, NULL);
    lv_obj_set_width(ui_Sound6, 40);
    lv_obj_set_height(ui_Sound6, 40);
    lv_obj_set_x(ui_Sound6, 518);
    lv_obj_set_y(ui_Sound6, 8);

    ui_Brightness6 = lv_imgbtn_create(ui_VOLUME);
    lv_imgbtn_set_src(ui_Brightness6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_388315622, NULL);
    lv_obj_set_width(ui_Brightness6, 50);
    lv_obj_set_height(ui_Brightness6, 50);
    lv_obj_set_x(ui_Brightness6, 567);
    lv_obj_set_y(ui_Brightness6, 3);

    ui_Setting6 = lv_imgbtn_create(ui_VOLUME);
    lv_imgbtn_set_src(ui_Setting6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1200060910, NULL);
    lv_obj_set_width(ui_Setting6, 40);
    lv_obj_set_height(ui_Setting6, 39);
    lv_obj_set_x(ui_Setting6, 626);
    lv_obj_set_y(ui_Setting6, 8);

    ui_Personal_volume = lv_imgbtn_create(ui_VOLUME);
    lv_imgbtn_set_src(ui_Personal_volume, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_personal_button_png, NULL);
    lv_obj_set_width(ui_Personal_volume, 80);
    lv_obj_set_height(ui_Personal_volume, 100);
    lv_obj_set_x(ui_Personal_volume, 711);
    lv_obj_set_y(ui_Personal_volume, 65);

    ui_Group_volume = lv_imgbtn_create(ui_VOLUME);
    lv_imgbtn_set_src(ui_Group_volume, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_button_png, NULL);
    lv_obj_set_width(ui_Group_volume, 80);
    lv_obj_set_height(ui_Group_volume, 100);
    lv_obj_set_x(ui_Group_volume, 711);
    lv_obj_set_y(ui_Group_volume, 195);

    ui_radio_volume = lv_imgbtn_create(ui_VOLUME);
    lv_imgbtn_set_src(ui_radio_volume, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radiopa_button_png, NULL);
    lv_obj_set_width(ui_radio_volume, 80);
    lv_obj_set_height(ui_radio_volume, 120);
    lv_obj_set_x(ui_radio_volume, 712);
    lv_obj_set_y(ui_radio_volume, 320);

    ui_logo_intercom_6 = lv_img_create(ui_VOLUME);
    lv_img_set_src(ui_logo_intercom_6, &ui_img_logo_navysis_png);
    lv_obj_set_width(ui_logo_intercom_6, LV_SIZE_CONTENT);   /// 613
    lv_obj_set_height(ui_logo_intercom_6, LV_SIZE_CONTENT);    /// 248
    lv_obj_set_align(ui_logo_intercom_6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_intercom_6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_intercom_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_popup_volume = lv_img_create(ui_VOLUME);
    lv_img_set_src(ui_popup_volume, &ui_img_popup_volume_updown_png);
    lv_obj_set_width(ui_popup_volume, LV_SIZE_CONTENT);   /// 450
    lv_obj_set_height(ui_popup_volume, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_popup_volume, 175);
    lv_obj_set_y(ui_popup_volume, 90);
    lv_obj_add_flag(ui_popup_volume, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_popup_volume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_volume = lv_label_create(ui_popup_volume);
    lv_obj_set_width(ui_Label_volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_volume, 19);
    lv_obj_set_y(ui_Label_volume, 10);
    lv_label_set_text(ui_Label_volume, "Volume");
    lv_obj_set_style_text_color(ui_Label_volume, lv_color_hex(0x234A81), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_volume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_volume, &ui_font_volume, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Adjust_Volume = lv_slider_create(ui_popup_volume);
    lv_slider_set_value(ui_Adjust_Volume, 72, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Adjust_Volume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Adjust_Volume, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_Adjust_Volume, 298);
    lv_obj_set_height(ui_Adjust_Volume, 10);
    lv_obj_set_x(ui_Adjust_Volume, 57);
    lv_obj_set_y(ui_Adjust_Volume, 52);
    lv_obj_set_style_bg_color(ui_Adjust_Volume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Adjust_Volume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Adjust_Volume, lv_color_hex(0x426392), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Adjust_Volume, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Adjust_Volume, lv_color_hex(0x234A81), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Adjust_Volume, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_value_volume = lv_label_create(ui_popup_volume);
    lv_obj_set_width(ui_value_volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value_volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value_volume, 403);
    lv_obj_set_y(ui_value_volume, 45);
    lv_label_set_text(ui_value_volume, "72");
    lv_obj_set_style_text_color(ui_value_volume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_value_volume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_value_volume, &ui_font_value, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttov_plus_volume = lv_imgbtn_create(ui_popup_volume);
    lv_imgbtn_set_src(ui_buttov_plus_volume, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_154043135, NULL);
    lv_obj_set_width(ui_buttov_plus_volume, 24);
    lv_obj_set_height(ui_buttov_plus_volume, 24);
    lv_obj_set_x(ui_buttov_plus_volume, 370);
    lv_obj_set_y(ui_buttov_plus_volume, 45);

    ui_buttov_min_volume = lv_imgbtn_create(ui_popup_volume);
    lv_imgbtn_set_src(ui_buttov_min_volume, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1738235521, NULL);
    lv_obj_set_width(ui_buttov_min_volume, 24);
    lv_obj_set_height(ui_buttov_min_volume, 24);
    lv_obj_set_x(ui_buttov_min_volume, 18);
    lv_obj_set_y(ui_buttov_min_volume, 45);

    ui_close_volume = lv_imgbtn_create(ui_popup_volume);
    lv_imgbtn_set_src(ui_close_volume, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2126526304, NULL);
    lv_obj_set_width(ui_close_volume, 30);
    lv_obj_set_height(ui_close_volume, 30);
    lv_obj_set_x(ui_close_volume, 415);
    lv_obj_set_y(ui_close_volume, 5);

    lv_obj_add_event_cb(ui_Brightness6, ui_event_Brightness6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Adjust_Volume, ui_event_Adjust_Volume, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Sound6, ui_event_Sound6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Adjust_Volume,ui_event_Adjust_Volume_changed_callback, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_buttov_plus_volume, ui_event_buttov_plus_volume_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_buttov_min_volume, ui_event_buttov_min_volume_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_close_volume, ui_event_close_volume_clicked, LV_EVENT_CLICKED, NULL);


}
