// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "../ui.h"

void ui_PERSONAL_INCALL_screen_init(void)
{
    ui_PERSONAL_INCALL = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PERSONAL_INCALL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PERSONAL_INCALL, lv_color_hex(0x1480BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERSONAL_INCALL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PERSONAL_INCALL, lv_color_hex(0x03303C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PERSONAL_INCALL, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_server_on3 = lv_imgbtn_create(ui_PERSONAL_INCALL);
    lv_imgbtn_set_src(ui_server_on3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lucide_server_png, NULL);
    lv_obj_set_height(ui_server_on3, 28);
    lv_obj_set_width(ui_server_on3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_server_on3, 20);
    lv_obj_set_y(ui_server_on3, 14);

    ui_Peta_FF3 = lv_label_create(ui_PERSONAL_INCALL);
    lv_obj_set_width(ui_Peta_FF3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peta_FF3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peta_FF3, 51);
    lv_obj_set_y(ui_Peta_FF3, 14);
    lv_label_set_text(ui_Peta_FF3, "PETA FF");
    lv_obj_set_style_text_color(ui_Peta_FF3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Peta_FF3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Peta_FF3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waktu3 = lv_label_create(ui_PERSONAL_INCALL);
    lv_obj_set_width(ui_Waktu3, 73);
    lv_obj_set_height(ui_Waktu3, 33);
    lv_obj_set_x(ui_Waktu3, 436);
    lv_obj_set_y(ui_Waktu3, 16);
    lv_label_set_text(ui_Waktu3, "08:00");
    lv_obj_set_style_text_color(ui_Waktu3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waktu3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waktu3, &ui_font_waktu, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sound3 = lv_imgbtn_create(ui_PERSONAL_INCALL);
    lv_imgbtn_set_src(ui_Sound3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1559931635, NULL);
    lv_obj_set_width(ui_Sound3, 40);
    lv_obj_set_height(ui_Sound3, 40);
    lv_obj_set_x(ui_Sound3, 518);
    lv_obj_set_y(ui_Sound3, 8);

    ui_Brightness3 = lv_imgbtn_create(ui_PERSONAL_INCALL);
    lv_imgbtn_set_src(ui_Brightness3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_388315622, NULL);
    lv_obj_set_width(ui_Brightness3, 50);
    lv_obj_set_height(ui_Brightness3, 50);
    lv_obj_set_x(ui_Brightness3, 567);
    lv_obj_set_y(ui_Brightness3, 3);

    ui_Setting3 = lv_imgbtn_create(ui_PERSONAL_INCALL);
    lv_imgbtn_set_src(ui_Setting3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1200060910, NULL);
    lv_obj_set_width(ui_Setting3, 40);
    lv_obj_set_height(ui_Setting3, 39);
    lv_obj_set_x(ui_Setting3, 626);
    lv_obj_set_y(ui_Setting3, 8);

    ui_Button_Personal3 = lv_imgbtn_create(ui_PERSONAL_INCALL);
    lv_imgbtn_set_src(ui_Button_Personal3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_personal_buttonn_png, NULL);
    lv_obj_set_width(ui_Button_Personal3, 80);
    lv_obj_set_height(ui_Button_Personal3, 100);
    lv_obj_set_x(ui_Button_Personal3, 711);
    lv_obj_set_y(ui_Button_Personal3, 65);

    ui_Buton_Group3 = lv_imgbtn_create(ui_PERSONAL_INCALL);
    lv_imgbtn_set_src(ui_Buton_Group3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_group_button_png, NULL);
    lv_obj_set_width(ui_Buton_Group3, 80);
    lv_obj_set_height(ui_Buton_Group3, 100);
    lv_obj_set_x(ui_Buton_Group3, 711);
    lv_obj_set_y(ui_Buton_Group3, 195);

    ui_Button_Radio3 = lv_imgbtn_create(ui_PERSONAL_INCALL);
    lv_imgbtn_set_src(ui_Button_Radio3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_radiopa_button_png, NULL);
    lv_obj_set_width(ui_Button_Radio3, 80);
    lv_obj_set_height(ui_Button_Radio3, 120);
    lv_obj_set_x(ui_Button_Radio3, 712);
    lv_obj_set_y(ui_Button_Radio3, 320);

    ui_logo_Intercom3 = lv_img_create(ui_PERSONAL_INCALL);
    lv_img_set_src(ui_logo_Intercom3, &ui_img_logo_navysis_png);
    lv_obj_set_width(ui_logo_Intercom3, LV_SIZE_CONTENT);   /// 613
    lv_obj_set_height(ui_logo_Intercom3, LV_SIZE_CONTENT);    /// 248
    lv_obj_set_align(ui_logo_Intercom3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_Intercom3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_Intercom3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_list_Personal_incall = lv_img_create(ui_PERSONAL_INCALL);
    lv_img_set_src(ui_list_Personal_incall, &ui_img_list_personal_incall_png);
    lv_obj_set_width(ui_list_Personal_incall, LV_SIZE_CONTENT);   /// 685
    lv_obj_set_height(ui_list_Personal_incall, LV_SIZE_CONTENT);    /// 415
    lv_obj_set_x(ui_list_Personal_incall, 7);
    lv_obj_set_y(ui_list_Personal_incall, 57);
    lv_obj_add_flag(ui_list_Personal_incall, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_list_Personal_incall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Kom_Anjungan_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_Kom_Anjungan_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_kom_anjgan_incall_png, NULL);
    lv_obj_set_width(ui_Kom_Anjungan_incall, 110);
    lv_obj_set_height(ui_Kom_Anjungan_incall, 100);

    ui_Palaksan_Anjungan_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_Palaksan_Anjungan_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_palaksa_incall_png, NULL);
    lv_obj_set_width(ui_Palaksan_Anjungan_incall, 110);
    lv_obj_set_height(ui_Palaksan_Anjungan_incall, 100);
    lv_obj_set_x(ui_Palaksan_Anjungan_incall, 115);
    lv_obj_set_y(ui_Palaksan_Anjungan_incall, 0);

    ui_CIC_ROOM_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_CIC_ROOM_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_cic_room_incall_png, NULL);
    lv_obj_set_width(ui_CIC_ROOM_incall, 110);
    lv_obj_set_height(ui_CIC_ROOM_incall, 100);
    lv_obj_set_x(ui_CIC_ROOM_incall, 230);
    lv_obj_set_y(ui_CIC_ROOM_incall, 0);

    ui_ECR_KA__incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_ECR_KA__incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_ecr_ka_incall_png, NULL);
    lv_obj_set_width(ui_ECR_KA__incall, 110);
    lv_obj_set_height(ui_ECR_KA__incall, 100);
    lv_obj_set_x(ui_ECR_KA__incall, 345);
    lv_obj_set_y(ui_ECR_KA__incall, 0);

    ui_ECR_KI_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_ECR_KI_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_ecr_ki_incall_png, NULL);
    lv_obj_set_width(ui_ECR_KI_incall, 110);
    lv_obj_set_height(ui_ECR_KI_incall, 100);
    lv_obj_set_x(ui_ECR_KI_incall, 460);
    lv_obj_set_y(ui_ECR_KI_incall, 0);

    ui_empty1_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty1_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty1_incall, 110);
    lv_obj_set_height(ui_empty1_incall, 100);
    lv_obj_set_x(ui_empty1_incall, 575);
    lv_obj_set_y(ui_empty1_incall, 0);

    ui_empty2_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty2_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty2_incall, 110);
    lv_obj_set_height(ui_empty2_incall, 100);
    lv_obj_set_x(ui_empty2_incall, 0);
    lv_obj_set_y(ui_empty2_incall, 105);

    ui_empty3_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty3_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty3_incall, 110);
    lv_obj_set_height(ui_empty3_incall, 100);
    lv_obj_set_x(ui_empty3_incall, 115);
    lv_obj_set_y(ui_empty3_incall, 105);

    ui_empty4_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty4_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty4_incall, 110);
    lv_obj_set_height(ui_empty4_incall, 100);
    lv_obj_set_x(ui_empty4_incall, 230);
    lv_obj_set_y(ui_empty4_incall, 105);

    ui_empty5_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty5_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty5_incall, 110);
    lv_obj_set_height(ui_empty5_incall, 100);
    lv_obj_set_x(ui_empty5_incall, 345);
    lv_obj_set_y(ui_empty5_incall, 105);

    ui_empty6_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty6_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty6_incall, 110);
    lv_obj_set_height(ui_empty6_incall, 100);
    lv_obj_set_x(ui_empty6_incall, 460);
    lv_obj_set_y(ui_empty6_incall, 105);

    ui_empty7_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty7_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty7_incall, 110);
    lv_obj_set_height(ui_empty7_incall, 100);
    lv_obj_set_x(ui_empty7_incall, 575);
    lv_obj_set_y(ui_empty7_incall, 105);

    ui_empty8_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty8_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty8_incall, 110);
    lv_obj_set_height(ui_empty8_incall, 100);
    lv_obj_set_x(ui_empty8_incall, 0);
    lv_obj_set_y(ui_empty8_incall, 210);

    ui_empty9_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty9_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty9_incall, 110);
    lv_obj_set_height(ui_empty9_incall, 100);
    lv_obj_set_x(ui_empty9_incall, 115);
    lv_obj_set_y(ui_empty9_incall, 210);

    ui_empty10_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty10_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty10_incall, 110);
    lv_obj_set_height(ui_empty10_incall, 100);
    lv_obj_set_x(ui_empty10_incall, 230);
    lv_obj_set_y(ui_empty10_incall, 210);

    ui_empty11_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty11_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty11_incall, 110);
    lv_obj_set_height(ui_empty11_incall, 100);
    lv_obj_set_x(ui_empty11_incall, 345);
    lv_obj_set_y(ui_empty11_incall, 210);

    ui_empty12_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty12_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty12_incall, 110);
    lv_obj_set_height(ui_empty12_incall, 100);
    lv_obj_set_x(ui_empty12_incall, 460);
    lv_obj_set_y(ui_empty12_incall, 210);

    ui_empty13_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty13_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty13_incall, 110);
    lv_obj_set_height(ui_empty13_incall, 100);
    lv_obj_set_x(ui_empty13_incall, 575);
    lv_obj_set_y(ui_empty13_incall, 210);

    ui_empty14_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty14_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty14_incall, 110);
    lv_obj_set_height(ui_empty14_incall, 100);
    lv_obj_set_x(ui_empty14_incall, 0);
    lv_obj_set_y(ui_empty14_incall, 315);

    ui_empty15_incall = lv_imgbtn_create(ui_list_Personal_incall);
    lv_imgbtn_set_src(ui_empty15_incall, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_14_png, NULL);
    lv_obj_set_width(ui_empty15_incall, 110);
    lv_obj_set_height(ui_empty15_incall, 100);
    lv_obj_set_x(ui_empty15_incall, 115);
    lv_obj_set_y(ui_empty15_incall, 315);

}
