// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
int sock_fd;
call_status_t call_state = idle;
unsigned char brightness_level = 100;
unsigned char volume_level = 100;
unsigned char is_long_pressed = 0;


// SCREEN: ui_Start_Up
void ui_Start_Up_screen_init(void);
lv_obj_t * ui_Start_Up;
lv_obj_t * ui_Logo_Interkom;
lv_obj_t * ui_loader;
lv_obj_t * ui_initializations;
lv_obj_t * ui____initial_actions0;

// SCREEN: ui_HOME
void ui_HOME_screen_init(void);
lv_obj_t * ui_HOME;
lv_obj_t * ui_server_on;
lv_obj_t * ui_Peta_FF;
lv_obj_t * ui_Waktu;
void ui_event_Sound(lv_event_t * e);
lv_obj_t * ui_Sound;
void ui_event_Brightness(lv_event_t * e);
lv_obj_t * ui_Brightness;
void ui_event_Setting(lv_event_t * e);
lv_obj_t * ui_Setting;
void ui_event_Personal_Home(lv_event_t * e);
lv_obj_t * ui_Personal_Home;
lv_obj_t * ui_Group_Home;
lv_obj_t * ui_radio_Home;
lv_obj_t * ui_logo_Intercom;
lv_obj_t * ui____initial_actions0;

// SCREEN: ui_PERSONAL_SELECT
void ui_PERSONAL_SELECT_screen_init(void);
lv_obj_t * ui_PERSONAL_SELECT;
lv_obj_t * ui_server_on1;
lv_obj_t * ui_Peta_FF1;
lv_obj_t * ui_Waktu1;
void ui_event_Sound1(lv_event_t * e);
lv_obj_t * ui_Sound1;
void ui_event_Brightness1(lv_event_t * e);
lv_obj_t * ui_Brightness1;
void ui_event_Setting1(lv_event_t * e);
lv_obj_t * ui_Setting1;
void ui_event_Personal_Select(lv_event_t * e);
lv_obj_t * ui_Personal_Select;
// void ui_event_Personal_Group_Select(lv_event_t * e);
lv_obj_t * ui_Personal_Group_Select;
// void ui_event_Personal_Radio_Select(lv_event_t * e);
lv_obj_t * ui_Personal_Radio_Select;
lv_obj_t * ui_logo_Intercom1;
lv_obj_t * ui_list_Personal_select;
void ui_event_Kom_Anjungan_select_clicked_callback(lv_event_t *e);
lv_obj_t * ui_Kom_Anjungan_select;
void ui_event_Palaksan_Anjungan_select_clicked_callback(lv_event_t *e);
lv_obj_t * ui_Palaksan_Anjungan_select;
void ui_event_CIC_ROOM_select_clicked_callback(lv_event_t *e);
lv_obj_t * ui_CIC_ROOM__select;
void ui_event_ECR_KA_select_clicked_callback(lv_event_t *e);
lv_obj_t * ui_ECR_KA__select;
void ui_event_ECR_KI_select_clicked_callback(lv_event_t *e);
lv_obj_t * ui_ECR_KI__select;
lv_obj_t * ui_empty_1;
lv_obj_t * ui_empty2;
lv_obj_t * ui_empty3;
lv_obj_t * ui_empty4;
lv_obj_t * ui_empty5;
lv_obj_t * ui_empty6;
lv_obj_t * ui_empty7;
lv_obj_t * ui_empty8;
lv_obj_t * ui_empty9;
lv_obj_t * ui_empty10;
lv_obj_t * ui_empty11;
lv_obj_t * ui_empty12;
lv_obj_t * ui_empty13;
lv_obj_t * ui_empty14;
lv_obj_t * ui_empty15;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_button_[1] = {&ui_img_button_14_png};

// SCREEN: ui_PERSONAL_CALL
void ui_PERSONAL_CALL_screen_init(void);
lv_obj_t * ui_PERSONAL_CALL;
lv_obj_t * ui_server_on2;
lv_obj_t * ui_Peta_FF2;
lv_obj_t * ui_Waktu2;
lv_obj_t * ui_Sound2;
lv_obj_t * ui_Brightness2;
lv_obj_t * ui_Setting2;
lv_obj_t * ui_Button_Personal2;
lv_obj_t * ui_Button_Group2;
lv_obj_t * ui_Button_Radio2;
lv_obj_t * ui_logo_Intercom2;
lv_obj_t * ui_list_Personal_call;
lv_obj_t * ui_Kom_Anjungan_call;
lv_obj_t * ui_Palaksan_Anjungan_call;
lv_obj_t * ui_CIC_ROOM_call;
lv_obj_t * ui_ECR_KA_call;
lv_obj_t * ui_ECR_KI_call;
lv_obj_t * ui_empty_call1;
lv_obj_t * ui_empty_call2;
lv_obj_t * ui_empty_call3;
lv_obj_t * ui_empty_call4;
lv_obj_t * ui_empty_call5;
lv_obj_t * ui_empty_call6;
lv_obj_t * ui_empty_call7;
lv_obj_t * ui_empty_call8;
lv_obj_t * ui_empty_call9;
lv_obj_t * ui_empty_call10;
lv_obj_t * ui_empty_call11;
lv_obj_t * ui_empty_call12;
lv_obj_t * ui_empty_call13;
lv_obj_t * ui_empty_Incall14;
lv_obj_t * ui_empty_Incall15;
lv_obj_t * ui____initial_actions0;


// SCREEN: ui_PERSONAL_INCALL
void ui_PERSONAL_INCALL_screen_init(void);
lv_obj_t * ui_PERSONAL_INCALL;
lv_obj_t * ui_server_on3;
lv_obj_t * ui_Peta_FF3;
lv_obj_t * ui_Waktu3;
lv_obj_t * ui_Sound3;
lv_obj_t * ui_Brightness3;
lv_obj_t * ui_Setting3;
lv_obj_t * ui_Button_Personal3;
lv_obj_t * ui_Buton_Group3;
lv_obj_t * ui_Button_Radio3;
lv_obj_t * ui_logo_Intercom3;
lv_obj_t * ui_list_Personal_incall;
lv_obj_t * ui_Kom_Anjungan_incall;
lv_obj_t * ui_Palaksan_Anjungan_incall;
lv_obj_t * ui_CIC_ROOM_incall;
lv_obj_t * ui_ECR_KA__incall;
lv_obj_t * ui_ECR_KI_incall;
lv_obj_t * ui_empty1_incall;
lv_obj_t * ui_empty2_incall;
lv_obj_t * ui_empty3_incall;
lv_obj_t * ui_empty4_incall;
lv_obj_t * ui_empty5_incall;
lv_obj_t * ui_empty6_incall;
lv_obj_t * ui_empty7_incall;
lv_obj_t * ui_empty8_incall;
lv_obj_t * ui_empty9_incall;
lv_obj_t * ui_empty10_incall;
lv_obj_t * ui_empty11_incall;
lv_obj_t * ui_empty12_incall;
lv_obj_t * ui_empty13_incall;
lv_obj_t * ui_empty14_incall;
lv_obj_t * ui_empty15_incall;
lv_obj_t * ui____initial_actions0;

// SCREEN: ui_GROUP_SELECT
void ui_GROUP_SELECT_screen_init(void);
lv_obj_t * ui_GROUP_SELECT;
lv_obj_t * ui_server_on4;
lv_obj_t * ui_Peta_FF4;
lv_obj_t * ui_Waktu4;
// void ui_event_Sound4(lv_event_t * e);
lv_obj_t * ui_Sound4;
// void ui_event_Brightness4(lv_event_t * e);
lv_obj_t * ui_Brightness4;
// void ui_event_Setting4(lv_event_t * e);
lv_obj_t * ui_Setting4;
// void ui_event_Personal_group(lv_event_t * e);
lv_obj_t * ui_Personal_group;
// void ui_event_Group_Select(lv_event_t * e);
lv_obj_t * ui_Group_Select;
// void ui_event_Radio_Group(lv_event_t * e);
lv_obj_t * ui_Radio_Group;
lv_obj_t * ui_logo_intercom_4;
lv_obj_t * ui_list_personal_group;
lv_obj_t * ui_group_pku;
lv_obj_t * ui_group_pk_sen;
lv_obj_t * ui_group_pk_ops;
lv_obj_t * ui_group_manuvra;
lv_obj_t * ui_group_pit;
lv_obj_t * ui_group_all;
lv_obj_t * ui_empty_group_select1;
lv_obj_t * ui_empty_group_select2;
lv_obj_t * ui_empty_group_select3;
lv_obj_t * ui_empty_group_select4;
lv_obj_t * ui_empty_group_select5;
lv_obj_t * ui_empty_group_select6;
lv_obj_t * ui_empty_group_select7;
lv_obj_t * ui_empty_group_select8;
lv_obj_t * ui_empty_group_select9;
lv_obj_t * ui_empty_group_select10;
lv_obj_t * ui_empty_group_select11;
lv_obj_t * ui_empty_group_select12;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_group_[6] = {&ui_img_group_2_png, &ui_img_group_3_png, &ui_img_group_4_png, &ui_img_group_5_png, &ui_img_group_6_png, &ui_img_group_8_png};

// SCREEN: ui_RADIO_SELECT
void ui_RADIO_SELECT_screen_init(void);
lv_obj_t * ui_RADIO_SELECT;
lv_obj_t * ui_server_on5;
lv_obj_t * ui_Peta_FF5;
lv_obj_t * ui_Waktu5;
// void ui_event_Sound5(lv_event_t * e);
lv_obj_t * ui_Sound5;
// void ui_event_Brightness5(lv_event_t * e);
lv_obj_t * ui_Brightness5;
// void ui_event_Setting5(lv_event_t * e);
lv_obj_t * ui_Setting5;
// void ui_event_Personal_Radio(lv_event_t * e);
lv_obj_t * ui_Personal_radio;
lv_obj_t * ui_Group_radio;
lv_obj_t * ui_Radiopa_select;
lv_obj_t * ui_logo_intercom_5;
lv_obj_t * ui_list_personal_radio;
lv_obj_t * ui_radio1;
lv_obj_t * ui_radio2;
lv_obj_t * ui_radio3;
lv_obj_t * ui_radio4;
lv_obj_t * ui_radio5;
lv_obj_t * ui_radio6;
lv_obj_t * ui_radio7;
lv_obj_t * ui_radio8;
lv_obj_t * ui_radio9;
lv_obj_t * ui_radio10;
lv_obj_t * ui_radioempty11;
lv_obj_t * ui_radioempty12;
lv_obj_t * ui_mainbroadcast;
lv_obj_t * ui_operatif;
lv_obj_t * ui_darurat;
lv_obj_t * ui_kebakaran;
lv_obj_t * ui_khusus;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_radio_kebakaran_incall[1] = {&ui_img_radio_kebakaran_incall14_png};
const lv_img_dsc_t * ui_imgset_radio_khusus_incall[1] = {&ui_img_radio_khusus_incall15_png};

// SCREEN: ui_VOLUME
void ui_VOLUME_screen_init(void);
lv_obj_t * ui_VOLUME;
lv_obj_t * ui_server_on6;
lv_obj_t * ui_Peta_FF6;
lv_obj_t * ui_Waktu6;
void ui_event_Sound6(lv_event_t * e);
lv_obj_t * ui_Sound6;
void ui_event_Brightness6(lv_event_t * e);
lv_obj_t * ui_Brightness6;
lv_obj_t * ui_Setting6;
lv_obj_t * ui_Personal_volume;
lv_obj_t * ui_Group_volume;
lv_obj_t * ui_radio_volume;
lv_obj_t * ui_logo_intercom_6;
lv_obj_t * ui_popup_volume;
lv_obj_t * ui_Label_volume;
void ui_event_Adjust_Volume(lv_event_t * e);
void ui_event_Adjust_Volume_changed_callback(lv_event_t *e);
lv_obj_t * ui_Adjust_Volume;
lv_obj_t * ui_value_volume;
void ui_event_buttov_plus_volume_clicked(lv_event_t * e);
lv_obj_t * ui_buttov_plus_volume;
void ui_event_buttov_min_volume_clicked(lv_event_t * e);
lv_obj_t * ui_buttov_min_volume;
void ui_event_close_volume_clicked(lv_event_t * e);
lv_obj_t * ui_close_volume;

// SCREEN: ui_BRIGHTNESS
void ui_BRIGHTNESS_screen_init(void);
lv_obj_t * ui_BRIGHTNESS;
lv_obj_t * ui_server_on7;
lv_obj_t * ui_Peta_FF7;
lv_obj_t * ui_Waktu7;
lv_obj_t * ui_Sound7;
void ui_event_Brightness7(lv_event_t * e);
lv_obj_t * ui_Brightness7;
lv_obj_t * ui_Setting7;
lv_obj_t * ui_Personal_brightness;
lv_obj_t * ui_Group_brightness;
lv_obj_t * ui_radio_brightness;
lv_obj_t * ui_logo_intercom_7;
lv_obj_t * ui_popup_brightness;
lv_obj_t * ui_Label_brightness;
void ui_event_Adjust_Brightness(lv_event_t * e);
void ui_event_Adjust_Brightness_changed_callback(lv_event_t *e);
lv_obj_t * ui_Adjust_Brightness;
lv_obj_t * ui_value_brightness;
lv_obj_t * ui_buttov_plus_brightness;
void ui_event_buttov_min_brightness_clicked(lv_event_t * e);
lv_obj_t * ui_buttov_min_brightness;
void ui_event_close_brightness_clicked(lv_event_t * e);
lv_obj_t * ui_close_brightness;
lv_obj_t * ui____initial_actions0;

// SCREEN: ui_SETTING
void ui_SETTING_screen_init(void);
lv_obj_t * ui_SETTING;
lv_obj_t * ui_server_on8;
lv_obj_t * ui_Peta_FF8;
lv_obj_t * ui_Waktu8;
lv_obj_t * ui_Sound8;
lv_obj_t * ui_Brightness8;
lv_obj_t * ui_Setting8;
lv_obj_t * ui_Personal_setting8;
lv_obj_t * ui_Group_setting8;
lv_obj_t * ui_radio_setting8;
lv_obj_t * ui_logo_intercom8;
lv_obj_t * ui_popup_setting8;
lv_obj_t * ui_Label_Setting8;
void ui_event_Button_Performance(lv_event_t * e);
lv_obj_t * ui_Button_Performance;
void ui_event_Button_Selftest(lv_event_t * e);
lv_obj_t * ui_Button_Selftest;
void ui_event_Button_About(lv_event_t * e);
lv_obj_t * ui_Button_About;
lv_obj_t * ui_Label_CPU;
lv_obj_t * ui_value_CPU;
lv_obj_t * ui_Label_Memory;
lv_obj_t * ui_value_Memory;
lv_obj_t * ui_grafik_CPU;
lv_obj_t * ui_Grafik_Memory;
lv_obj_t * ui____initial_actions0;

// SCREEN: ui_SELFTEST
void ui_SELFTEST_screen_init(void);
lv_obj_t * ui_SELFTEST;
lv_obj_t * ui_server_on9;
lv_obj_t * ui_Peta_FF9;
lv_obj_t * ui_Waktu9;
lv_obj_t * ui_Sound9;
lv_obj_t * ui_Brightness9;
lv_obj_t * ui_Setting9;
lv_obj_t * ui_Personal_setting9;
lv_obj_t * ui_Group_setting9;
lv_obj_t * ui_radio_setting9;
lv_obj_t * ui_logo_intercom9;
lv_obj_t * ui_popup_setting9;
lv_obj_t * ui_Label_Setting9;
void ui_event_Button_Performance1(lv_event_t * e);
lv_obj_t * ui_Button_Performance1;
void ui_event_Button_Selftest1(lv_event_t * e);
lv_obj_t * ui_Button_Selftest1;
void ui_event_Button_About1(lv_event_t * e);
lv_obj_t * ui_Button_About1;
lv_obj_t * ui_Label_Selftest;
lv_obj_t * ui____initial_actions0;

// SCREEN: ui_ABOUT
void ui_ABOUT_screen_init(void);
lv_obj_t * ui_ABOUT;
lv_obj_t * ui_server_on10;
lv_obj_t * ui_Peta_FF10;
lv_obj_t * ui_Waktu10;
lv_obj_t * ui_Sound10;
lv_obj_t * ui_Brightness10;
lv_obj_t * ui_Setting10;
lv_obj_t * ui_Personal_setting10;
lv_obj_t * ui_Group_setting10;
lv_obj_t * ui_radio_setting10;
lv_obj_t * ui_logo_intercom10;
lv_obj_t * ui_popup_setting10;
lv_obj_t * ui_Label_Setting10;
void ui_event_Button_Performance2(lv_event_t * e);
lv_obj_t * ui_Button_Performance2;
void ui_event_Button_Selftest2(lv_event_t * e);
lv_obj_t * ui_Button_Selftest2;
void ui_event_Button_About2(lv_event_t * e);
lv_obj_t * ui_Button_About2;
lv_obj_t * ui_Label_Information;
lv_obj_t * ui_Label_software;
lv_obj_t * ui_Label_Version;
lv_obj_t * ui_logo;
lv_obj_t * ui_value_versi;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
///////////////////// FUNCTIONS MENU HOME ////////////////////
void ui_event_Sound(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(ui_VOLUME, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Brightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(ui_BRIGHTNESS, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(ui_SETTING, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
    }
}
void ui_event_Personal_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(ui_PERSONAL_SELECT, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
    }
}
///////////////////// FUNCTIONS MENU PERSONAL ////////////////////
void ui_event_Personal_Select(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
    }
}
// void ui_event_Personal_Group_Select(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_RELEASED) {
//         _ui_screen_change(ui_GROUP_SELECT, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
//     }
// }
// void ui_event_Personal_Radio_Select(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_RELEASED) {
//         _ui_screen_change(ui_RADIO_SELECT, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
//     }
// }

void ui_event_Sound1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(ui_VOLUME, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
    }
}
void ui_event_Brightness1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(ui_BRIGHTNESS, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
    }
}
void ui_event_Setting1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(ui_SETTING, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
    }
}


///////////////////// FUNCTIONS MENU GROUP ////////////////////
// void ui_event_Sound4(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_RELEASED) {
//         _ui_screen_change(ui_VOLUME, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
//     }
// }
// void ui_event_Brightness4(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_RELEASED) {
//         _ui_screen_change(ui_BRIGHTNESS, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
//     }
// }
// void ui_event_Setting4(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_RELEASED) {
//         _ui_screen_change(ui_SETTING, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
//     }
// }
// void ui_event_Personal_group(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_RELEASED) {
//         _ui_screen_change(ui_PERSONAL_SELECT, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
//     }
// }
// void ui_event_Group_Select(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_RELEASED) {
//         _ui_screen_change(ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
//     }
// }
// void ui_event_Radio_Group(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_RELEASED) {
//         _ui_screen_change(ui_RADIO_SELECT, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0);
//     }
// }
///////////////////// FUNCTIONS SOUND ////////////////////
void ui_event_Sound6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Brightness6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_BRIGHTNESS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Adjust_Volume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_value_volume, target, "", "");
    }
}

void ui_event_buttov_plus_volume_clicked(lv_event_t * e)
{
    int value = lv_slider_get_value(ui_Adjust_Volume);
    if (value < 100) {
        value++;
        lv_slider_set_value(ui_Adjust_Volume, value, LV_ANIM_ON);
    }
    lv_event_send(ui_Adjust_Volume, LV_EVENT_VALUE_CHANGED, NULL);
}

void ui_event_buttov_min_volume_clicked(lv_event_t * e)
{
    int value = lv_slider_get_value(ui_Adjust_Volume);
    if (value > 0) {
        value--;
        lv_slider_set_value(ui_Adjust_Volume, value, LV_ANIM_ON);
    }
    lv_event_send(ui_Adjust_Volume, LV_EVENT_VALUE_CHANGED, NULL);
}

void ui_event_close_volume_clicked(lv_event_t * e)
{
    lv_obj_add_flag(ui_popup_volume, LV_OBJ_FLAG_HIDDEN);
}





///////////////////// FUNCTIONS BRIGHTNESSS ////////////////////
void ui_event_Brightness7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Adjust_Brightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_value_brightness, target, "", "");
    }
}

void ui_event_buttov_plus_brightness_clicked(lv_event_t * e)
{
    int value = lv_slider_get_value(ui_Adjust_Brightness);
    if (value < 100) {
        value++;
        lv_slider_set_value(ui_Adjust_Brightness, value, LV_ANIM_ON);
    }
    lv_event_send(ui_Adjust_Brightness, LV_EVENT_VALUE_CHANGED, NULL);
}

void ui_event_buttov_min_brightness_clicked(lv_event_t * e)
{
    int value = lv_slider_get_value(ui_Adjust_Brightness);
    if (value > 0) {
        value--;
        lv_slider_set_value(ui_Adjust_Brightness, value, LV_ANIM_ON);
    }
    lv_event_send(ui_Adjust_Brightness, LV_EVENT_VALUE_CHANGED, NULL);
}

void ui_event_close_brightness_clicked(lv_event_t * e)
{
    lv_obj_add_flag(ui_popup_brightness, LV_OBJ_FLAG_HIDDEN);
}


///////////////////// SETTING ////////////////////
void ui_event_Setting8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button_Performance(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button_Selftest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_SELFTEST, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button_Performance1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_SETTING, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button_About(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_ABOUT, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button_About1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_ABOUT, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}

void ui_event_Button_Selftest1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_SETTING, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}

void ui_event_Button_Performance2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_SETTING, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button_Selftest2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_SELFTEST, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}
void ui_event_Button_About2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_SETTING, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
    }
}

///////////////////// fungsi TCP/IP Client  ////////////////////

void command_handler (int fd, unsigned char *buffer, unsigned char length)
{
   int ret;
   unsigned char cmd_buffer[200];
   unsigned char cmd_length = 0;

// [0x25][0x53/0x47][CMD_IDX][VALUE][0xFF][0xFF] ==> Protocol Format

   switch (buffer[1]) {
       case 0x53:              // command SET
           switch (buffer[2]) {
               case 0x01:      // CALL command
                   if (buffer[3] == 0x00) {
                       printf("Unable to call / call not succeed\n");
                   } else {
                        lv_imgbtn_set_src(ui_Kom_Anjungan_call, LV_IMGBTN_STATE_RELEASED, &ui_img_button_kom_anjgan_call_png,NULL, NULL);
                        lv_imgbtn_set_src(ui_Palaksan_Anjungan_call, LV_IMGBTN_STATE_RELEASED, &ui_img_button_palaksa_call_png,NULL, NULL);
                        lv_imgbtn_set_src(ui_CIC_ROOM_call, LV_IMGBTN_STATE_RELEASED, &ui_img_button_cic_room_call_png, NULL, NULL);
                        lv_imgbtn_set_src(ui_ECR_KA_call, LV_IMGBTN_STATE_RELEASED, &ui_img_button_ecr_ka_call_png, NULL, NULL);
                        lv_imgbtn_set_src(ui_ECR_KI_call, LV_IMGBTN_STATE_RELEASED, &ui_img_button_ecr_ki_call_png, NULL, NULL);
                       // set tombol background menjadi kuning karena sedang dalam mencoba memanggil keluar
                       // berdasarkan id tombol sesuai dengan nilai dari buffer[3]
                   }
                   break;
               case 0x02:      // TERMINATE command
                        lv_imgbtn_set_src(ui_Kom_Anjungan_select, LV_IMGBTN_STATE_RELEASED, &ui_img_komandan_anjungan_home_png,NULL, NULL);
                        lv_imgbtn_set_src(ui_Palaksan_Anjungan_select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_palaksa_anjgan_home_png,NULL, NULL);
                        lv_imgbtn_set_src(ui_CIC_ROOM__select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_cic_room_home_png, NULL, NULL);
                        lv_imgbtn_set_src(ui_ECR_KA__select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_r_ecr_ka_home_png, NULL, NULL);
                        lv_imgbtn_set_src(ui_ECR_KI__select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_r_ecr_ki_home_png, NULL, NULL);   
                   // set background tombol menjadi biru (idle) kembali setelah di terminate dan sukses berdasarkan
                   // id tombol yang sesuai dengan nilai dari buffer[3]
                   break;
               case 0x03:      // REJECT command
                        lv_imgbtn_set_src(ui_Kom_Anjungan_select, LV_IMGBTN_STATE_RELEASED, &ui_img_komandan_anjungan_home_png,NULL, NULL);
                        lv_imgbtn_set_src(ui_Palaksan_Anjungan_select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_palaksa_anjgan_home_png,NULL, NULL);
                        lv_imgbtn_set_src(ui_CIC_ROOM__select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_cic_room_home_png, NULL, NULL);
                        lv_imgbtn_set_src(ui_ECR_KA__select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_r_ecr_ka_home_png, NULL, NULL);
                        lv_imgbtn_set_src(ui_ECR_KI__select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_r_ecr_ki_home_png, NULL, NULL); 
                   // set background tombol menjadi biru (idle) kembali setelah di terminate dan sukses berdasarkan
                   // id tombol yang sesuai dengan nilai dari buffer[3]
                   break;
               case 0x04:      // ACCEPT command
                        lv_imgbtn_set_src(ui_Kom_Anjungan_incall, LV_IMGBTN_STATE_RELEASED, &ui_img_button_kom_anjgan_incall_png,NULL, NULL);
                        lv_imgbtn_set_src(ui_Palaksan_Anjungan_incall, LV_IMGBTN_STATE_RELEASED, &ui_img_button_palaksa_incall_png,NULL, NULL);
                        lv_imgbtn_set_src(ui_CIC_ROOM_incall, LV_IMGBTN_STATE_RELEASED, &ui_img_button_cic_room_incall_png, NULL, NULL);
                        lv_imgbtn_set_src(ui_ECR_KA__incall, LV_IMGBTN_STATE_RELEASED, &ui_img_button_ecr_ka_incall_png, NULL, NULL);
                        lv_imgbtn_set_src(ui_ECR_KI_incall, LV_IMGBTN_STATE_RELEASED, &ui_img_button_ecr_ki_incall_png, NULL, NULL); 
                   // set background tombol menjadi hijau (call connected) kembali setelah di terminate dan sukses berdasarkan
                   // id tombol yang sesuai dengan nilai dari buffer[3]
                   break;
               case 0x05:      // CALL STATE command
                   // do nothing
                   break;
               case 0x06:      // BRIGHTNESS command
                   printf("Success to set brightness value to core apps\n");
                   break;
               case 0x07:      // VOLUME command
                   printf("Success to set volume value to core apps\n");
                   break;
               case 0x08:      // BUTTON command
                   switch (buffer[3]) {            // button id (1 - 5)
                       case 1:                     // button id 1
                           switch (buffer[4]) {    // button state (0: idle, 1: calling, 2: established, 3: incoming call, 4: disconnected / rejected / end call)
                               case 0:
                               lv_imgbtn_set_src(ui_Kom_Anjungan_select, LV_IMGBTN_STATE_RELEASED, &ui_img_komandan_anjungan_home_png,NULL,NULL);
                                   // ubah tombol id 1 menjadi background biru (idle)
                                   break;
                               case 1:
                               lv_imgbtn_set_src(ui_Kom_Anjungan_call, LV_IMGBTN_STATE_RELEASED, &ui_img_button_kom_anjgan_call_png, NULL,NULL);
                                   // ubah tombol id 1 menjadi background kuning (calling)
                                   break;
                               case 2:
                                lv_imgbtn_set_src(ui_Kom_Anjungan_incall, LV_IMGBTN_STATE_RELEASED, &ui_img_button_kom_anjgan_incall_png, NULL,NULL);
                                   // ubah tombol id 1 menjadi background hijau (established / on call)
                                   break;
                               case 3:
                               
                                   // ubah tombol id 1 menjadi background kuning blinking (incoming call)
                                   break;
                               case 4:
                                   // ubah tombol id 1 menjadi background merah (discnnected/reject/end)
                                   break;
                           }
                           break;
                       case 2:                     // button id 2
                           switch (buffer[4]) {    // button state (0: idle, 1: calling, 2: established, 3: incoming call, 4: disconnected / rejected / end call)
                               case 0:
                               lv_imgbtn_set_src(ui_Palaksan_Anjungan_select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_palaksa_anjgan_home_png,NULL,NULL);
                                   // ubah tombol id 2 menjadi background biru (idle)
                                   break;
                               case 1:
                               lv_imgbtn_set_src(ui_Palaksan_Anjungan_call, LV_IMGBTN_STATE_RELEASED, &ui_img_button_palaksa_call_png,NULL, NULL);
                                   // ubah tombol id 2 menjadi background kuning (calling)
                                   break;
                               case 2:
                               lv_imgbtn_set_src(ui_Palaksan_Anjungan_incall, LV_IMGBTN_STATE_RELEASED, &ui_img_button_palaksa_incall_png,NULL, NULL);
                                   // ubah tombol id 2 menjadi background hijau (established / on call)
                                   break;
                               case 3:
                                   // ubah tombol id 2 menjadi background kuning blinking (incoming call)
                                   break;
                               case 4:
                                   // ubah tombol id 2 menjadi background merah (discnnected/reject/end)
                                   break;
                           }
                           break;
                       case 3:                     // button id 3
                           switch (buffer[4]) {    // button state (0: idle, 1: calling, 2: established, 3: incoming call, 4: disconnected / rejected / end call)
                        case 0:
                        lv_imgbtn_set_src(ui_CIC_ROOM__select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_cic_room_home_png, NULL, NULL);
                                   // ubah tombol id 3 menjadi background biru (idle)
                                   break;
                               case 1:
                               lv_imgbtn_set_src(ui_CIC_ROOM_call, LV_IMGBTN_STATE_RELEASED, &ui_img_button_cic_room_call_png, NULL, NULL);
                                   // ubah tombol id 3 menjadi background kuning (calling)
                                   break;
                               case 2:
                               lv_imgbtn_set_src(ui_CIC_ROOM_incall, LV_IMGBTN_STATE_RELEASED, &ui_img_button_cic_room_incall_png, NULL, NULL);
                                   // ubah tombol id 3 menjadi background hijau (established / on call)
                                   break;
                               case 3:
                                   // ubah tombol id 3 menjadi background kuning blinking (incoming call)
                                   break;
                               case 4:
                                   // ubah tombol id 3 menjadi background merah (discnnected/reject/end)
                                   break;
                           }
                           break;
                       case 4:                     // button id 4
                           switch (buffer[4]) {    // button state (0: idle, 1: calling, 2: established, 3: incoming call, 4: disconnected / rejected / end call)
                               case 0:
                               lv_imgbtn_set_src(ui_ECR_KA__select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_r_ecr_ka_home_png, NULL, NULL);
                                   // ubah tombol id 4 menjadi background biru (idle)
                                   break;
                               case 1:
                               lv_imgbtn_set_src(ui_ECR_KA_call, LV_IMGBTN_STATE_RELEASED, &ui_img_button_ecr_ka_call_png, NULL, NULL);
                                   // ubah tombol id 4 menjadi background kuning (calling)
                                   break;
                               case 2:
                               lv_imgbtn_set_src(ui_ECR_KA__incall, LV_IMGBTN_STATE_RELEASED, &ui_img_button_ecr_ka_incall_png, NULL, NULL);
                                   // ubah tombol id 4 menjadi background hijau (established / on call)
                                   break;
                               case 3:
                                   // ubah tombol id 4 menjadi background kuning blinking (incoming call)
                                   break;
                               case 4:
                                   // ubah tombol id 4 menjadi background merah (discnnected/reject/end)
                                   break;
                           }
                           break;
                       case 5:                     // button id 5
                           switch (buffer[4]) {    // button state (0: idle, 1: calling, 2: established, 3: incoming call, 4: disconnected / rejected / end call)
                               case 0:
                               lv_imgbtn_set_src(ui_ECR_KI__select, LV_IMGBTN_STATE_RELEASED, &ui_img_button_r_ecr_ki_home_png, NULL, NULL); 
                                   // ubah tombol id 5 menjadi background biru (idle)
                                   break;
                               case 1:
                               lv_imgbtn_set_src(ui_ECR_KI_call, LV_IMGBTN_STATE_RELEASED, &ui_img_button_ecr_ki_call_png, NULL, NULL);
                                   // ubah tombol id 5 menjadi background kuning (calling)
                                   break;
                               case 2:
                                lv_imgbtn_set_src(ui_ECR_KI_incall, LV_IMGBTN_STATE_RELEASED, &ui_img_button_ecr_ki_incall_png, NULL, NULL); 
                                   // ubah tombol id 5 menjadi background hijau (established / on call)
                                   break;
                               case 3:
                                   // ubah tombol id 5 menjadi background kuning blinking (incoming call)
                                   break;
                               case 4:
                                   // ubah tombol id 5 menjadi background merah (discnnected/reject/end)
                                   break;
                           }
                           break;
                   }

                   cmd_buffer[0] = 0x25;           // header protocol
                   cmd_buffer[1] = 0x53;           // command SET
                   cmd_buffer[2] = 0x08;           // command index BUTTON
                   cmd_buffer[3] = buffer[3];       // value BUTTON_ID
                   cmd_buffer[4] = 0xFF;           // footer protocol
                   cmd_buffer[5] = 0xFF;           // footer protocol
                   cmd_length = 6;
                   break;
           }
break;
       case 0x47:              // command GET
           switch (buffer[2]) {
               case 0x05:      // CALL STATE command
                   if ((buffer[3] >= (unsigned char)idle) && (buffer[3] <= (unsigned char)terminate)) {
                       call_state = (call_status_t)buffer[3];
                   }
                   break;
               case 0x06:      // BRIGHTNESS command
                   if ((buffer[3] >= 0) && (buffer[3] <= 100)) {
                       brightness_level = buffer[3];
                   }
                   break;
               case 0x07:      // VOLUME command
                   if ((buffer[3] >= 0) && (buffer[3] <= 100)) {
                       volume_level = buffer[3];
                   }
                   break;
           }
           break;
   }

   if (cmd_length > 0) {
       ret = write(fd, cmd_buffer, cmd_length);
       if (ret < 0) {
           printf("Error: Failed to write to TCP/IP Server Socket\n");
       }
   }
}

void *tcp_client_thread (void *args)
{
   int ret;
   struct sockaddr_in server;
   int yes = 1;
   struct pollfd fdset;
   unsigned char received_buffer[200];
   unsigned char buffer[2];
   unsigned char received_buffer_count = 0;

REINIT:
   sock_fd = socket(AF_INET, SOCK_STREAM, 0);
if (sock_fd < 0) {
       printf("Error: Failed to create socket connection\n");
   }

   if (setsockopt(sock_fd, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes)) == -1) {
       printf("Error: Failed to configure socket to auto-reuse if closed unexpectedly\n");
   }

RECONNECT:
   server.sin_family = AF_INET;
   server.sin_addr.s_addr = inet_addr("127.0.0.1");
   server.sin_port = htons(12345);

   if (connect(sock_fd, (struct sockaddr *)&server, sizeof(server)) != 0) {
       printf("Error: Failed to connect to TCP/IP server\n");
       sleep(1);
       goto RECONNECT;
   } else {
       printf("Success to connect to TCP/IP server\n");
   }

   fdset.fd = sock_fd;
   fdset.events = POLLIN | POLLPRI;
   memset(received_buffer, '\0', sizeof(received_buffer));
   memset(buffer, '\0', sizeof(buffer));
   received_buffer_count = 0;

   for (;;) {
       ret = poll(&fdset, 1, 100);
       if (ret < 0) {
           printf("Error: Failed to poll TCP/IP socket\n");
       }

       if (fdset.revents & (POLLIN | POLLPRI)) {
           lseek(sock_fd, 0, SEEK_SET);
           ret = recv(sock_fd, buffer, 1, 0);
           if (ret > 0) {
               if ((received_buffer[0] == 0x25) && (received_buffer[received_buffer_count] == 0xFF) && (buffer[0] == 0xFF)) {
command_handler(sock_fd, received_buffer, received_buffer_count);
                   memset(received_buffer, '\0', sizeof(received_buffer));
                   received_buffer_count = 0;
               }
               else if (received_buffer[0] == 0x25) {
                   received_buffer_count++;
                   received_buffer[received_buffer_count] = buffer[0];
               }
               else if (buffer[0] == 0x25) {
                   received_buffer_count = 0;
                   received_buffer[received_buffer_count] = buffer[0];
               }
           }
           else if (ret < 0) {
               printf("Error: Failed to receive data from TCP/IP Server socket\n");
           }
           else {
               printf("Error: Disconnected from TCP/IP Server\n");
               sock_fd = 0;
               goto REINIT;
               break;
           }
       }
   }
}

///////////////////// FUNGSI BUTTON KOM ANJUNGAN CLICKED ////////////////////
void ui_event_Kom_Anjungan_select_clicked_callback(lv_event_t *e)
{
   lv_event_code_t code = lv_event_get_code(e);
   unsigned char cmd_buffer[100];
   unsigned char cmd_length = 0;
   int ret;

   switch (code) {
       case LV_EVENT_CLICKED:
           if (is_long_pressed == 1) {
               is_long_pressed = 0;
               return;
           }

           cmd_buffer[0] = 0x25;               // header protocol
           cmd_buffer[1] = 0x53;               // command SET
           cmd_buffer[3] = 0x01;               // button id
           cmd_buffer[4] = 0xFF;               // footer protocol
           cmd_buffer[5] = 0xFF;               // footer protocol
           if (call_state == idle) {
               cmd_buffer[2] = 0x01;           // command index for Initiate CALL
               cmd_length = 6;                 // send command
           }
           else if (call_state == incoming_call) {
               cmd_buffer[2] = 0x04;           // command index for Accept CALL
               cmd_length = 6;                 // send command
           }
           else {
               cmd_length = 0;                 // dont send anything
           }
           break;
       case LV_EVENT_LONG_PRESSED:
           is_long_pressed = 1;

           cmd_buffer[0] = 0x25;               // header protocol
           cmd_buffer[1] = 0x53;               // command SET
           cmd_buffer[3] = 0x01;               // button id
           cmd_buffer[4] = 0xFF;               // footer protocol
           cmd_buffer[5] = 0xFF;               // footer protocol
           if (call_state == established) {
               cmd_buffer[2] = 0x02;           // command index for Terminate CALL  
               cmd_length = 6;
           }
           else if (call_state == incoming_call) {
               cmd_buffer[2] = 0x03;           // command index for Reject CALL
               cmd_length = 6;
           }
           else {
               cmd_length = 0;                 // dont send anything
           }
           break;
   }

   if (cmd_length > 0) {
       ret = write(sock_fd, cmd_buffer, cmd_length);
       if (ret < 0) {
           printf("Error: Failed to send command to Core Apps\n");
       }
   }
}
///////////////////// FUNGSI BUTTON PALAKSA ANJUNGAN CLICKED ////////////////////
void ui_event_Palaksan_Anjungan_select_clicked_callback(lv_event_t *e)
{
   lv_event_code_t code = lv_event_get_code(e);
   unsigned char cmd_buffer[100];
   unsigned char cmd_length = 0;
   int ret;

   switch (code) {
       case LV_EVENT_CLICKED:
           if (is_long_pressed == 1) {
               is_long_pressed = 0;
               return;
           }

           cmd_buffer[0] = 0x25;               // header protocol
           cmd_buffer[1] = 0x53;               // command SET
           cmd_buffer[3] = 0x01;               // button id
           cmd_buffer[4] = 0xFF;               // footer protocol
           cmd_buffer[5] = 0xFF;               // footer protocol
           if (call_state == idle) {
               cmd_buffer[2] = 0x01;           // command index for Initiate CALL
               cmd_length = 6;                 // send command
           }
           else if (call_state == incoming_call) {
               cmd_buffer[2] = 0x04;           // command index for Accept CALL
               cmd_length = 6;                 // send command
           }
           else {
               cmd_length = 0;                 // dont send anything
           }
           break;
       case LV_EVENT_LONG_PRESSED:
           is_long_pressed = 1;

           cmd_buffer[0] = 0x25;               // header protocol
           cmd_buffer[1] = 0x53;               // command SET
           cmd_buffer[3] = 0x01;               // button id
           cmd_buffer[4] = 0xFF;               // footer protocol
           cmd_buffer[5] = 0xFF;               // footer protocol
           if (call_state == established) {
               cmd_buffer[2] = 0x02;           // command index for Terminate CALL  
               cmd_length = 6;
           }
           else if (call_state == incoming_call) {
               cmd_buffer[2] = 0x03;           // command index for Reject CALL
               cmd_length = 6;
           }
           else {
               cmd_length = 0;                 // dont send anything
           }
           break;
   }

   if (cmd_length > 0) {
       ret = write(sock_fd, cmd_buffer, cmd_length);
       if (ret < 0) {
           printf("Error: Failed to send command to Core Apps\n");
       }
   }
}
///////////////////// FUNGSI BUTTON CIC ROOM CLICKED ////////////////////
void ui_event_CIC_ROOM_select_clicked_callback(lv_event_t *e)
{
   lv_event_code_t code = lv_event_get_code(e);
   unsigned char cmd_buffer[100];
   unsigned char cmd_length = 0;
   int ret;

   switch (code) {
       case LV_EVENT_CLICKED:
           if (is_long_pressed == 1) {
               is_long_pressed = 0;
               return;
           }

           cmd_buffer[0] = 0x25;               // header protocol
           cmd_buffer[1] = 0x53;               // command SET
           cmd_buffer[3] = 0x01;               // button id
           cmd_buffer[4] = 0xFF;               // footer protocol
           cmd_buffer[5] = 0xFF;               // footer protocol
           if (call_state == idle) {
               cmd_buffer[2] = 0x01;           // command index for Initiate CALL
               cmd_length = 6;                 // send command
           }
           else if (call_state == incoming_call) {
               cmd_buffer[2] = 0x04;           // command index for Accept CALL
               cmd_length = 6;                 // send command
           }
           else {
               cmd_length = 0;                 // dont send anything
           }
           break;
       case LV_EVENT_LONG_PRESSED:
           is_long_pressed = 1;

           cmd_buffer[0] = 0x25;               // header protocol
           cmd_buffer[1] = 0x53;               // command SET
           cmd_buffer[3] = 0x01;               // button id
           cmd_buffer[4] = 0xFF;               // footer protocol
           cmd_buffer[5] = 0xFF;               // footer protocol
           if (call_state == established) {
               cmd_buffer[2] = 0x02;           // command index for Terminate CALL  
               cmd_length = 6;
           }
           else if (call_state == incoming_call) {
               cmd_buffer[2] = 0x03;           // command index for Reject CALL
               cmd_length = 6;
           }
           else {
               cmd_length = 0;                 // dont send anything
           }
           break;
   }

   if (cmd_length > 0) {
       ret = write(sock_fd, cmd_buffer, cmd_length);
       if (ret < 0) {
           printf("Error: Failed to send command to Core Apps\n");
       }
   }
}

///////////////////// FUNGSI BUTTON ECR KA CLICKED ////////////////////
void ui_event_ECR_KA_select_clicked_callback(lv_event_t *e)
{
   lv_event_code_t code = lv_event_get_code(e);
   unsigned char cmd_buffer[100];
   unsigned char cmd_length = 0;
   int ret;

   switch (code) {
       case LV_EVENT_CLICKED:
           if (is_long_pressed == 1) {
               is_long_pressed = 0;
               return;
           }

           cmd_buffer[0] = 0x25;               // header protocol
           cmd_buffer[1] = 0x53;               // command SET
           cmd_buffer[3] = 0x01;               // button id
           cmd_buffer[4] = 0xFF;               // footer protocol
           cmd_buffer[5] = 0xFF;               // footer protocol
           if (call_state == idle) {
               cmd_buffer[2] = 0x01;           // command index for Initiate CALL
               cmd_length = 6;                 // send command
           }
           else if (call_state == incoming_call) {
               cmd_buffer[2] = 0x04;           // command index for Accept CALL
               cmd_length = 6;                 // send command
           }
           else {
               cmd_length = 0;                 // dont send anything
           }
           break;
       case LV_EVENT_LONG_PRESSED:
           is_long_pressed = 1;

           cmd_buffer[0] = 0x25;               // header protocol
           cmd_buffer[1] = 0x53;               // command SET
           cmd_buffer[3] = 0x01;               // button id
           cmd_buffer[4] = 0xFF;               // footer protocol
           cmd_buffer[5] = 0xFF;               // footer protocol
           if (call_state == established) {
               cmd_buffer[2] = 0x02;           // command index for Terminate CALL  
               cmd_length = 6;
           }
           else if (call_state == incoming_call) {
               cmd_buffer[2] = 0x03;           // command index for Reject CALL
               cmd_length = 6;
           }
           else {
               cmd_length = 0;                 // dont send anything
           }
           break;
   }

   if (cmd_length > 0) {
       ret = write(sock_fd, cmd_buffer, cmd_length);
       if (ret < 0) {
           printf("Error: Failed to send command to Core Apps\n");
       }
   }
}
///////////////////// FUNGSI BUTTON ECR KI CLICKED ////////////////////
void ui_event_ECR_KI_select_clicked_callback(lv_event_t *e)
{
   lv_event_code_t code = lv_event_get_code(e);
   unsigned char cmd_buffer[100];
   unsigned char cmd_length = 0;
   int ret;

   switch (code) {
       case LV_EVENT_CLICKED:
           if (is_long_pressed == 1) {
               is_long_pressed = 0;
               return;
           }

           cmd_buffer[0] = 0x25;               // header protocol
           cmd_buffer[1] = 0x53;               // command SET
           cmd_buffer[3] = 0x01;               // button id
           cmd_buffer[4] = 0xFF;               // footer protocol
           cmd_buffer[5] = 0xFF;               // footer protocol
           if (call_state == idle) {
               cmd_buffer[2] = 0x01;           // command index for Initiate CALL
               cmd_length = 6;                 // send command
           }
           else if (call_state == incoming_call) {
               cmd_buffer[2] = 0x04;           // command index for Accept CALL
               cmd_length = 6;                 // send command
           }
           else {
               cmd_length = 0;                 // dont send anything
           }
           break;
       case LV_EVENT_LONG_PRESSED:
           is_long_pressed = 1;

           cmd_buffer[0] = 0x25;               // header protocol
           cmd_buffer[1] = 0x53;               // command SET
           cmd_buffer[3] = 0x01;               // button id
           cmd_buffer[4] = 0xFF;               // footer protocol
           cmd_buffer[5] = 0xFF;               // footer protocol
           if (call_state == established) {
               cmd_buffer[2] = 0x02;           // command index for Terminate CALL  
               cmd_length = 6;
           }
           else if (call_state == incoming_call) {
               cmd_buffer[2] = 0x03;           // command index for Reject CALL
               cmd_length = 6;
           }
           else {
               cmd_length = 0;                 // dont send anything
           }
           break;
   }

   if (cmd_length > 0) {
       ret = write(sock_fd, cmd_buffer, cmd_length);
       if (ret < 0) {
           printf("Error: Failed to send command to Core Apps\n");
       }
   }
}

///////////////////// SET BRIGHTNESS LEVEL ////////////////////
void ui_event_Adjust_Brightness_changed_callback(lv_event_t *e)
{
   lv_event_code_t code = lv_event_get_code(e);
   lv_obj_t *slider = lv_event_get_target(e);
   unsigned char cmd_buffer[100];
   int ret;

   if (code == LV_EVENT_VALUE_CHANGED) {
       cmd_buffer[0] = 0x25;               // header protocol
       cmd_buffer[1] = 0x53;               // command SET
       cmd_buffer[2] = 0x06;               // command index for BRIGHTNESS
       cmd_buffer[3] = (unsigned char)lv_slider_get_value(slider); // brightness value
       cmd_buffer[4] = 0xFF;               // footer protocol
       cmd_buffer[5] = 0xFF;               // footer protocol
       ret = write(sock_fd, cmd_buffer, 6);
       if (ret < 0) {
           printf("Error: Failed to write command to Core Apps\n");
       }
   }
}

///////////////////// SET VOLUME LEVEL ////////////////////
void ui_event_Adjust_Volume_changed_callback(lv_event_t *e)
{
   lv_event_code_t code = lv_event_get_code(e);
   lv_obj_t *slider = lv_event_get_target(e);
   unsigned char cmd_buffer[100];
   int ret;
   if (code == LV_EVENT_VALUE_CHANGED) {
       cmd_buffer[0] = 0x25;               // header protocol
       cmd_buffer[1] = 0x53;               // command SET
       cmd_buffer[2] = 0x07;               // command index for VOLUME
       cmd_buffer[3] = (unsigned char)lv_slider_get_value(slider); // volume value
       cmd_buffer[4] = 0xFF;               // footer protocol
       cmd_buffer[5] = 0xFF;               // footer protocol
       ret = write(sock_fd, cmd_buffer, 6);
       if (ret < 0) {
           printf("Error: Failed to write command to Core Apps\n");
       }
   }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Start_Up_screen_init();
    ui_HOME_screen_init();
    ui_PERSONAL_SELECT_screen_init();
    // ui_PERSONAL_INCALL_screen_init();
    ui_PERSONAL_CALL_screen_init();
    ui_GROUP_SELECT_screen_init();
     ui_RADIO_SELECT_screen_init();
    ui_VOLUME_screen_init();
    ui_BRIGHTNESS_screen_init();
    ui_SETTING_screen_init();
    ui_SELFTEST_screen_init();
    ui_ABOUT_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    // lv_disp_load_scr(ui_HOME);
    lv_disp_load_scr(ui_HOME);
}