// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: UI

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <unistd.h>
#include <poll.h>
#include <fcntl.h>
#include <signal.h>
#include <string.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <net/if.h>

extern int sock_fd;

typedef enum {
   idle=0,
   calling, established, incoming_call, reject, terminate
} call_status_t;

extern call_status_t call_state;
extern unsigned char brightness_level;
extern unsigned char volume_level;
extern unsigned char is_long_pressed;

void *tcp_client_thread (void *args);
void command_handler (int fd, unsigned char *buffer, unsigned char length);


// SCREEN: ui_Start_Up
void ui_Start_Up_screen_init(void);
extern lv_obj_t * ui_Start_Up;
extern lv_obj_t * ui_Logo_Interkom;
extern lv_obj_t * ui_loader;
extern lv_obj_t * ui_initializations;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_icon_png);    // assets/Icon.png

LV_FONT_DECLARE(ui_font_CPU);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_MHz);
LV_FONT_DECLARE(ui_font_about);
LV_FONT_DECLARE(ui_font_pabx);
LV_FONT_DECLARE(ui_font_roboto_medium);
LV_FONT_DECLARE(ui_font_setting);
LV_FONT_DECLARE(ui_font_value);
LV_FONT_DECLARE(ui_font_volume);
LV_FONT_DECLARE(ui_font_waktu);

// SCREEN: ui_HOME
void ui_HOME_screen_init(void);
extern lv_obj_t * ui_HOME;
extern lv_obj_t * ui_server_on;
extern lv_obj_t * ui_Peta_FF;
extern lv_obj_t * ui_Waktu;
void ui_event_Sound(lv_event_t * e);
extern lv_obj_t * ui_Sound;
void ui_event_Brightness(lv_event_t * e);
extern lv_obj_t * ui_Brightness;
void ui_event_Setting(lv_event_t * e);
extern lv_obj_t * ui_Setting;
void ui_event_Personal_Home(lv_event_t * e);
extern lv_obj_t * ui_Personal_Home;
extern lv_obj_t * ui_Group_Home;
extern lv_obj_t * ui_radio_Home;
extern lv_obj_t * ui_logo_Intercom;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_1200060910);    // assets/ci_settings-filled.png
LV_IMG_DECLARE(ui_img_personal_button_png);    // assets/PERSONAL BUTTON.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radiopa_button_png);    // assets/RADIOPA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png

// SCREEN: ui_PERSONAL_SELECT
void ui_PERSONAL_SELECT_screen_init(void);
extern lv_obj_t * ui_PERSONAL_SELECT;
extern lv_obj_t * ui_server_on1;
extern lv_obj_t * ui_Peta_FF1;
extern lv_obj_t * ui_Waktu1;
void ui_event_Sound1(lv_event_t * e);
extern lv_obj_t * ui_Sound1;
void ui_event_Brightness1(lv_event_t * e);
extern lv_obj_t * ui_Brightness1;
void ui_event_Setting1(lv_event_t * e);
extern lv_obj_t * ui_Setting1;
void ui_event_Personal_Select(lv_event_t * e);
extern lv_obj_t * ui_Personal_Select;
// void ui_event_Personal_Group_Select(lv_event_t * e);
extern lv_obj_t * ui_Personal_Group_Select;
// void ui_event_Personal_Radio_Select(lv_event_t * e);
extern lv_obj_t * ui_Personal_Radio_Select;
extern lv_obj_t * ui_logo_Intercom1;
extern lv_obj_t * ui_list_Personal_select;
void ui_event_Kom_Anjungan_select_clicked_callback(lv_event_t *e);
extern lv_obj_t * ui_Kom_Anjungan_select;
void ui_event_Palaksan_Anjungan_select_clicked_callback(lv_event_t *e);
extern lv_obj_t * ui_Palaksan_Anjungan_select;
void ui_event_CIC_ROOM_select_clicked_callback(lv_event_t *e);
extern lv_obj_t * ui_CIC_ROOM__select;
void ui_event_ECR_KA_select_clicked_callback(lv_event_t *e);
extern lv_obj_t * ui_ECR_KA__select;
void ui_event_ECR_KI_select_clicked_callback(lv_event_t *e);
extern lv_obj_t * ui_ECR_KI__select;
extern lv_obj_t * ui_empty_1;
extern lv_obj_t * ui_empty2;
extern lv_obj_t * ui_empty3;
extern lv_obj_t * ui_empty4;
extern lv_obj_t * ui_empty5;
extern lv_obj_t * ui_empty6;
extern lv_obj_t * ui_empty7;
extern lv_obj_t * ui_empty8;
extern lv_obj_t * ui_empty9;
extern lv_obj_t * ui_empty10;
extern lv_obj_t * ui_empty11;
extern lv_obj_t * ui_empty12;
extern lv_obj_t * ui_empty13;
extern lv_obj_t * ui_empty14;
extern lv_obj_t * ui_empty15;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_1200060910);    // assets/ci_settings-filled.png
LV_IMG_DECLARE(ui_img_personal_buttonn_png);    // assets/PERSONAL BUTTONN.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radiopa_button_png);    // assets/RADIOPA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png
LV_IMG_DECLARE(ui_img_list_personal_incall_png);    // assets/List Personal Incall.png
LV_IMG_DECLARE(ui_img_komandan_anjungan_home_png);    // assets/KOMANDAN ANJUNGAN HOME.png
LV_IMG_DECLARE(ui_img_button_palaksa_anjgan_home_png);    // assets/BUTTON PALAKSA ANJGAN HOME.png
LV_IMG_DECLARE(ui_img_button_cic_room_home_png);    // assets/BUTTON CIC ROOM HOME.png
LV_IMG_DECLARE(ui_img_button_r_ecr_ka_home_png);    // assets/BUTTON R.ECR KA HOME.png
LV_IMG_DECLARE(ui_img_button_r_ecr_ki_home_png);    // assets/BUTTON R.ECR KI HOME.png
LV_IMG_DECLARE(ui_img_button_14_png);    // assets/Button_14.png

// SCREEN: ui_PERSONAL_CALL
void ui_PERSONAL_CALL_screen_init(void);
extern lv_obj_t * ui_PERSONAL_CALL;
extern lv_obj_t * ui_server_on2;
extern lv_obj_t * ui_Peta_FF2;
extern lv_obj_t * ui_Waktu2;
extern lv_obj_t * ui_Sound2;
extern lv_obj_t * ui_Brightness2;
extern lv_obj_t * ui_Setting2;
extern lv_obj_t * ui_Button_Personal2;
extern lv_obj_t * ui_Button_Group2;
extern lv_obj_t * ui_Button_Radio2;
extern lv_obj_t * ui_logo_Intercom2;
extern lv_obj_t * ui_list_Personal_call;
extern lv_obj_t * ui_Kom_Anjungan_call;
extern lv_obj_t * ui_Palaksan_Anjungan_call;
extern lv_obj_t * ui_CIC_ROOM_call;
extern lv_obj_t * ui_ECR_KA_call;
extern lv_obj_t * ui_ECR_KI_call;
extern lv_obj_t * ui_empty_call1;
extern lv_obj_t * ui_empty_call2;
extern lv_obj_t * ui_empty_call3;
extern lv_obj_t * ui_empty_call4;
extern lv_obj_t * ui_empty_call5;
extern lv_obj_t * ui_empty_call6;
extern lv_obj_t * ui_empty_call7;
extern lv_obj_t * ui_empty_call8;
extern lv_obj_t * ui_empty_call9;
extern lv_obj_t * ui_empty_call10;
extern lv_obj_t * ui_empty_call11;
extern lv_obj_t * ui_empty_call12;
extern lv_obj_t * ui_empty_call13;
extern lv_obj_t * ui_empty_Incall14;
extern lv_obj_t * ui_empty_Incall15;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_1200060910);    // assets/ci_settings-filled.png
LV_IMG_DECLARE(ui_img_personal_buttonn_png);    // assets/PERSONAL BUTTONN.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radiopa_button_png);    // assets/RADIOPA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png
LV_IMG_DECLARE(ui_img_list_personal_incall_png);    // assets/List Personal Incall.png
LV_IMG_DECLARE(ui_img_button_kom_anjgan_call_png);    // assets/BUTTON KOM ANJGAN CALL.png
LV_IMG_DECLARE(ui_img_button_palaksa_call_png);    // assets/BUTTON PALAKSA CALL.png
LV_IMG_DECLARE(ui_img_button_cic_room_call_png);    // assets/BUTTON CIC ROOM CALL.png
LV_IMG_DECLARE(ui_img_button_ecr_ka_call_png);    // assets/BUTTON ECR KA CALL.png
LV_IMG_DECLARE(ui_img_button_ecr_ki_call_png);    // assets/BUTTON ECR KI CALL.png
LV_IMG_DECLARE(ui_img_button_14_png);    // assets/Button_14.png

// SCREEN: ui_PERSONAL_INCALL
void ui_PERSONAL_INCALL_screen_init(void);
extern lv_obj_t * ui_PERSONAL_INCALL;
extern lv_obj_t * ui_server_on3;
extern lv_obj_t * ui_Peta_FF3;
extern lv_obj_t * ui_Waktu3;
extern lv_obj_t * ui_Sound3;
extern lv_obj_t * ui_Brightness3;
extern lv_obj_t * ui_Setting3;
extern lv_obj_t * ui_Button_Personal3;
extern lv_obj_t * ui_Buton_Group3;
extern lv_obj_t * ui_Button_Radio3;
extern lv_obj_t * ui_logo_Intercom3;
extern lv_obj_t * ui_list_Personal_incall;
extern lv_obj_t * ui_Kom_Anjungan_incall;
extern lv_obj_t * ui_Palaksan_Anjungan_incall;
extern lv_obj_t * ui_CIC_ROOM_incall;
extern lv_obj_t * ui_ECR_KA__incall;
extern lv_obj_t * ui_ECR_KI_incall;
extern lv_obj_t * ui_empty1_incall;
extern lv_obj_t * ui_empty2_incall;
extern lv_obj_t * ui_empty3_incall;
extern lv_obj_t * ui_empty4_incall;
extern lv_obj_t * ui_empty5_incall;
extern lv_obj_t * ui_empty6_incall;
extern lv_obj_t * ui_empty7_incall;
extern lv_obj_t * ui_empty8_incall;
extern lv_obj_t * ui_empty9_incall;
extern lv_obj_t * ui_empty10_incall;
extern lv_obj_t * ui_empty11_incall;
extern lv_obj_t * ui_empty12_incall;
extern lv_obj_t * ui_empty13_incall;
extern lv_obj_t * ui_empty14_incall;
extern lv_obj_t * ui_empty15_incall;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_1200060910);    // assets/ci_settings-filled.png
LV_IMG_DECLARE(ui_img_personal_buttonn_png);    // assets/PERSONAL BUTTONN.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radiopa_button_png);    // assets/RADIOPA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png
LV_IMG_DECLARE(ui_img_list_personal_incall_png);    // assets/List Personal Incall.png
LV_IMG_DECLARE(ui_img_button_kom_anjgan_incall_png);    // assets/BUTTON KOM ANJGAN INCALL.png
LV_IMG_DECLARE(ui_img_button_palaksa_incall_png);    // assets/BUTTON PALAKSA INCALL.png
LV_IMG_DECLARE(ui_img_button_cic_room_incall_png);    // assets/BUTTON CIC ROOM INCALL.png
LV_IMG_DECLARE(ui_img_button_ecr_ka_incall_png);    // assets/BUTTON ECR KA INCALL.png
LV_IMG_DECLARE(ui_img_button_ecr_ki_incall_png);    // assets/BUTTON ECR KI INCALL.png
LV_IMG_DECLARE(ui_img_button_14_png);    // assets/Button_14.png


// SCREEN: ui_GROUP_SELECT
void ui_GROUP_SELECT_screen_init(void);
extern lv_obj_t * ui_GROUP_SELECT;
extern lv_obj_t * ui_server_on4;
extern lv_obj_t * ui_Peta_FF4;
extern lv_obj_t * ui_Waktu4;
// void ui_event_Sound4(lv_event_t * e);
extern lv_obj_t * ui_Sound4;
// void ui_event_Brightness4(lv_event_t * e);
extern lv_obj_t * ui_Brightness4;
// void ui_event_Setting4(lv_event_t * e);
extern lv_obj_t * ui_Setting4;
// void ui_event_Personal_group(lv_event_t * e);
extern lv_obj_t * ui_Personal_group;
// void ui_event_Group_Select(lv_event_t * e);
extern lv_obj_t * ui_Group_Select;
// void ui_event_Radio_Group(lv_event_t * e);
extern lv_obj_t * ui_Radio_Group;
extern lv_obj_t * ui_logo_intercom_4;
extern lv_obj_t * ui_list_personal_group;
extern lv_obj_t * ui_group_pku;
extern lv_obj_t * ui_group_pk_sen;
extern lv_obj_t * ui_group_pk_ops;
extern lv_obj_t * ui_group_manuvra;
extern lv_obj_t * ui_group_pit;
extern lv_obj_t * ui_group_all;
extern lv_obj_t * ui_empty_group_select1;
extern lv_obj_t * ui_empty_group_select2;
extern lv_obj_t * ui_empty_group_select3;
extern lv_obj_t * ui_empty_group_select4;
extern lv_obj_t * ui_empty_group_select5;
extern lv_obj_t * ui_empty_group_select6;
extern lv_obj_t * ui_empty_group_select7;
extern lv_obj_t * ui_empty_group_select8;
extern lv_obj_t * ui_empty_group_select9;
extern lv_obj_t * ui_empty_group_select10;
extern lv_obj_t * ui_empty_group_select11;
extern lv_obj_t * ui_empty_group_select12;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_1200060910);    // assets/ci_settings-filled.png
LV_IMG_DECLARE(ui_img_personal_button_select_png);    // assets/PERSONAL BUTTON Select.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radiopa_button_png);    // assets/RADIOPA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png
LV_IMG_DECLARE(ui_img_list_group_png);    // assets/List_Group.png
LV_IMG_DECLARE(ui_img_group_8_png);    // assets/Group_8.png
LV_IMG_DECLARE(ui_img_group_2_png);    // assets/Group_2.png
LV_IMG_DECLARE(ui_img_group_3_png);    // assets/Group_3.png
LV_IMG_DECLARE(ui_img_group_4_png);    // assets/Group_4.png
LV_IMG_DECLARE(ui_img_group_5_png);    // assets/Group_5.png
LV_IMG_DECLARE(ui_img_group_6_png);    // assets/Group_6.png
LV_IMG_DECLARE(ui_img_empty_calling_1__png);    // assets/empty calling 1 .png
LV_IMG_DECLARE(ui_img_empty_calling_2_png);    // assets/empty calling 2.png
LV_IMG_DECLARE(ui_img_empty_calling_3_png);    // assets/empty calling 3.png
LV_IMG_DECLARE(ui_img_empty_calling_4_png);    // assets/empty calling 4.png
LV_IMG_DECLARE(ui_img_empty_calling_5_png);    // assets/empty calling 5.png
LV_IMG_DECLARE(ui_img_empty_calling_6__png);    // assets/empty calling 6 .png
LV_IMG_DECLARE(ui_img_empty_calling_7_png);    // assets/empty calling 7.png
LV_IMG_DECLARE(ui_img_empty_calling_8_png);    // assets/empty calling 8.png
LV_IMG_DECLARE(ui_img_empty_calling_9_png);    // assets/empty calling 9.png
LV_IMG_DECLARE(ui_img_empty_calling_10_png);    // assets/empty calling 10.png
LV_IMG_DECLARE(ui_img_empty_calling_11_png);    // assets/empty calling 11.png
LV_IMG_DECLARE(ui_img_empty_calling_12_png);    // assets/empty calling 12.png
LV_IMG_DECLARE(ui_img_empty_calling_13_png);    // assets/empty calling 13.png
LV_IMG_DECLARE(ui_img_empty_calling_14_png);    // assets/empty calling 14.png

// SCREEN: ui_RADIO_SELECT
void ui_RADIO_SELECT_screen_init(void);
extern lv_obj_t * ui_RADIO_SELECT;
extern lv_obj_t * ui_server_on5;
extern lv_obj_t * ui_Peta_FF5;
extern lv_obj_t * ui_Waktu5;
extern lv_obj_t * ui_Sound5;
extern lv_obj_t * ui_Brightness5;
extern lv_obj_t * ui_Setting5;
extern lv_obj_t * ui_Personal_radio;
extern lv_obj_t * ui_Group_radio;
extern lv_obj_t * ui_Radiopa_select;
extern lv_obj_t * ui_logo_intercom_5;
extern lv_obj_t * ui_list_personal_radio;
extern lv_obj_t * ui_radio1;
extern lv_obj_t * ui_radio2;
extern lv_obj_t * ui_radio3;
extern lv_obj_t * ui_radio4;
extern lv_obj_t * ui_radio5;
extern lv_obj_t * ui_radio6;
extern lv_obj_t * ui_radio7;
extern lv_obj_t * ui_radio8;
extern lv_obj_t * ui_radio9;
extern lv_obj_t * ui_radio10;
extern lv_obj_t * ui_radioempty11;
extern lv_obj_t * ui_radioempty12;
extern lv_obj_t * ui_mainbroadcast;
extern lv_obj_t * ui_operatif;
extern lv_obj_t * ui_darurat;
extern lv_obj_t * ui_kebakaran;
extern lv_obj_t * ui_khusus;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_1200060910);    // assets/ci_settings-filled.png
LV_IMG_DECLARE(ui_img_personal_button_png);    // assets/PERSONAL BUTTON.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radio_pa_button_png);    // assets/RADIO PA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png
LV_IMG_DECLARE(ui_img_list_group_png);    // assets/List_Group.png
LV_IMG_DECLARE(ui_img_radio_operatif_incall1_png);    // assets/Radio Operatif incall1.png
LV_IMG_DECLARE(ui_img_radio_operatif_incall2_png);    // assets/Radio Operatif incall2.png
LV_IMG_DECLARE(ui_img_radio_operatif_incall3_png);    // assets/Radio Operatif incall3.png
LV_IMG_DECLARE(ui_img_radio_operatif_incall4_png);    // assets/Radio Operatif incall4.png
LV_IMG_DECLARE(ui_img_radio_operatif_incall5_png);    // assets/Radio Operatif incall5.png
LV_IMG_DECLARE(ui_img_radio_operatif_incall7_png);    // assets/Radio Operatif incall7.png
LV_IMG_DECLARE(ui_img_radio_operatif_incall8_png);    // assets/Radio Operatif incall8.png
LV_IMG_DECLARE(ui_img_radio_operatif_incall9_png);    // assets/Radio Operatif incall9.png
LV_IMG_DECLARE(ui_img_radio_operatif_incall10_png);    // assets/Radio Operatif incall10.png
LV_IMG_DECLARE(ui_img_empty_calling_5_png);    // assets/empty calling 5.png
LV_IMG_DECLARE(ui_img_empty_calling_6__png);    // assets/empty calling 6 .png
LV_IMG_DECLARE(ui_img_radio_mainbroadcest_incall17_png);    // assets/Radio Mainbroadcest incall17.png
LV_IMG_DECLARE(ui_img_frame_12_png);    // assets/Frame 12.png
LV_IMG_DECLARE(ui_img_frame_13_png);    // assets/Frame 13.png
LV_IMG_DECLARE(ui_img_radio_kebakaran_incall14_png);    // assets/Radio Kebakaran incall14.png
LV_IMG_DECLARE(ui_img_radio_khusus_incall15_png);    // assets/Radio khusus incall15.png
LV_IMG_DECLARE(ui_img_empty_calling_10_png);    // assets/empty calling 10.png
LV_IMG_DECLARE(ui_img_empty_calling_11_png);    // assets/empty calling 11.png
LV_IMG_DECLARE(ui_img_empty_calling_12_png);    // assets/empty calling 12.png
LV_IMG_DECLARE(ui_img_empty_calling_13_png);    // assets/empty calling 13.png
LV_IMG_DECLARE(ui_img_empty_calling_14_png);    // assets/empty calling 14.png
LV_IMG_DECLARE(ui_img_empty_calling_2_png);    // assets/empty calling 2.png
LV_IMG_DECLARE(ui_img_empty_calling_3_png);    // assets/empty calling 3.png
LV_IMG_DECLARE(ui_img_empty_calling_4_png);    // assets/empty calling 4.png
LV_IMG_DECLARE(ui_img_empty_calling_7_png);    // assets/empty calling 7.png
LV_IMG_DECLARE(ui_img_empty_calling_8_png);    // assets/empty calling 8.png
LV_IMG_DECLARE(ui_img_empty_calling_9_png);    // assets/empty calling 9.png
LV_IMG_DECLARE(ui_img_group_2_png);    // assets/Group_2.png
LV_IMG_DECLARE(ui_img_group_3_png);    // assets/Group_3.png
LV_IMG_DECLARE(ui_img_group_5_png);    // assets/Group_5.png
LV_IMG_DECLARE(ui_img_group_4_png);    // assets/Group_4.png
LV_IMG_DECLARE(ui_img_group_6_png);    // assets/Group_6.png
LV_IMG_DECLARE(ui_img_group_8_png);    // assets/Group_8.png
LV_IMG_DECLARE(ui_img_radio_operatif_incall6_png);    // assets/Radio Operatif incall6.png

// SCREEN: ui_VOLUME
void ui_VOLUME_screen_init(void);
extern lv_obj_t * ui_VOLUME;
extern lv_obj_t * ui_server_on6;
extern lv_obj_t * ui_Peta_FF6;
extern lv_obj_t * ui_Waktu6;
void ui_event_Sound6(lv_event_t * e);
extern lv_obj_t * ui_Sound6;
void ui_event_Brightness6(lv_event_t * e);
extern lv_obj_t * ui_Brightness6;
extern lv_obj_t * ui_Setting6;
extern lv_obj_t * ui_Personal_volume;
extern lv_obj_t * ui_Group_volume;
extern lv_obj_t * ui_radio_volume;
extern lv_obj_t * ui_logo_intercom_6;
extern lv_obj_t * ui_popup_volume;
extern lv_obj_t * ui_Label_volume;
void ui_event_Adjust_Volume(lv_event_t * e);
void ui_event_Adjust_Volume_changed_callback(lv_event_t *e);
extern lv_obj_t * ui_Adjust_Volume;
extern lv_obj_t * ui_value_volume;
void ui_event_buttov_plus_volume_clicked(lv_event_t * e);
extern lv_obj_t * ui_buttov_plus_volume;
void ui_event_buttov_min_volume_clicked(lv_event_t * e);
extern lv_obj_t * ui_buttov_min_volume;
void ui_event_close_volume_clicked(lv_event_t * e);
extern lv_obj_t * ui_close_volume;

// SCREEN: ui_BRIGHTNESS
void ui_BRIGHTNESS_screen_init(void);
extern lv_obj_t * ui_BRIGHTNESS;
extern lv_obj_t * ui_server_on7;
extern lv_obj_t * ui_Peta_FF7;
extern lv_obj_t * ui_Waktu7;
extern lv_obj_t * ui_Sound7;
void ui_event_Brightness7(lv_event_t * e);
extern lv_obj_t * ui_Brightness7;
extern lv_obj_t * ui_Setting7;
extern lv_obj_t * ui_Personal_brightness;
extern lv_obj_t * ui_Group_brightness;
extern lv_obj_t * ui_radio_brightness;
extern lv_obj_t * ui_logo_intercom_7;
extern lv_obj_t * ui_popup_brightness;
extern lv_obj_t * ui_Label_brightness;
void ui_event_Adjust_Brightness(lv_event_t * e);
void ui_event_Adjust_Brightness_changed_callback(lv_event_t *e);
extern lv_obj_t * ui_Adjust_Brightness;
extern lv_obj_t * ui_value_brightness;
void ui_event_buttov_plus_brightness_clicked(lv_event_t * e);
extern lv_obj_t * ui_buttov_plus_brightness;
void ui_event_buttov_min_brightness_clicked(lv_event_t * e);
extern lv_obj_t * ui_buttov_min_brightness;
void ui_event_close_brightness_clicked(lv_event_t * e);
extern lv_obj_t * ui_close_brightness;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_824966301);    // assets/majesticons_sound-up(1).png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_1200060910);    // assets/ci_settings-filled.png
LV_IMG_DECLARE(ui_img_personal_button_png);    // assets/PERSONAL BUTTON.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radiopa_button_png);    // assets/RADIOPA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png
LV_IMG_DECLARE(ui_img_popup_volume_updown_png);    // assets/Popup Volume UpDown.png
LV_IMG_DECLARE(ui_img_154043135);    // assets/akar-icons_circle-plus.png
LV_IMG_DECLARE(ui_img_1738235521);    // assets/akar-icons_circle-minus.png
LV_IMG_DECLARE(ui_img_2126526304);    // assets/carbon_close-filled.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_brightness_png);    // assets/brightness.png

// SCREEN: ui_SETTING
void ui_SETTING_screen_init(void);
extern lv_obj_t * ui_SETTING;
extern lv_obj_t * ui_server_on8;
extern lv_obj_t * ui_Peta_FF8;
extern lv_obj_t * ui_Waktu8;
extern lv_obj_t * ui_Sound8;
extern lv_obj_t * ui_Brightness8;
void ui_event_Setting8(lv_event_t * e);
extern lv_obj_t * ui_Setting8;
extern lv_obj_t * ui_Personal_setting8;
extern lv_obj_t * ui_Group_setting8;
extern lv_obj_t * ui_radio_setting8;
extern lv_obj_t * ui_logo_intercom8;
extern lv_obj_t * ui_popup_setting8;
extern lv_obj_t * ui_Label_Setting8;
void ui_event_Button_Performance(lv_event_t * e);
extern lv_obj_t * ui_Button_Performance;
void ui_event_Button_Selftest(lv_event_t * e);
extern lv_obj_t * ui_Button_Selftest;
void ui_event_Button_About(lv_event_t * e);
extern lv_obj_t * ui_Button_About;
extern lv_obj_t * ui_Label_CPU;
extern lv_obj_t * ui_value_CPU;
extern lv_obj_t * ui_Label_Memory;
extern lv_obj_t * ui_value_Memory;
extern lv_obj_t * ui_grafik_CPU;
extern lv_obj_t * ui_Grafik_Memory;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_111514558);    // assets/ci_settings-filled(1).png
LV_IMG_DECLARE(ui_img_personal_button_png);    // assets/PERSONAL BUTTON.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radiopa_button_png);    // assets/RADIOPA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png
LV_IMG_DECLARE(ui_img_popup_set_png);    // assets/POPUP SET.png
LV_IMG_DECLARE(ui_img_button_performance_png);    // assets/Button Performance.png
LV_IMG_DECLARE(ui_img_1693904590);    // assets/Selftest(2).png
LV_IMG_DECLARE(ui_img_55024288);    // assets/Button About(1).png
LV_IMG_DECLARE(ui_img_frame_grafik_cpu_png);    // assets/Frame Grafik CPU.png
LV_IMG_DECLARE(ui_img_frame_grafik_memory_png);    // assets/Frame Grafik Memory.png

// SCREEN: ui_SELFTEST
void ui_SELFTEST_screen_init(void);
extern lv_obj_t * ui_SELFTEST;
extern lv_obj_t * ui_server_on9;
extern lv_obj_t * ui_Peta_FF9;
extern lv_obj_t * ui_Waktu9;
extern lv_obj_t * ui_Sound9;
extern lv_obj_t * ui_Brightness9;
extern lv_obj_t * ui_Setting9;
extern lv_obj_t * ui_Personal_setting9;
extern lv_obj_t * ui_Group_setting9;
extern lv_obj_t * ui_radio_setting9;
extern lv_obj_t * ui_logo_intercom9;
extern lv_obj_t * ui_popup_setting9;
extern lv_obj_t * ui_Label_Setting9;
void ui_event_Button_Performance1(lv_event_t * e);
extern lv_obj_t * ui_Button_Performance1;
void ui_event_Button_Selftest1(lv_event_t * e);
extern lv_obj_t * ui_Button_Selftest1;
void ui_event_Button_About1(lv_event_t * e);
extern lv_obj_t * ui_Button_About1;
extern lv_obj_t * ui_Label_Selftest;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_111514558);    // assets/ci_settings-filled(1).png
LV_IMG_DECLARE(ui_img_personal_button_png);    // assets/PERSONAL BUTTON.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radiopa_button_png);    // assets/RADIOPA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png
LV_IMG_DECLARE(ui_img_popup_set_png);    // assets/POPUP SET.png
LV_IMG_DECLARE(ui_img_430847109);    // assets/Button Performance(1).png
LV_IMG_DECLARE(ui_img_1930036399);    // assets/Button Selftest(1).png
LV_IMG_DECLARE(ui_img_55024288);    // assets/Button About(1).png

// SCREEN: ui_ABOUT
void ui_ABOUT_screen_init(void);
extern lv_obj_t * ui_ABOUT;
extern lv_obj_t * ui_server_on10;
extern lv_obj_t * ui_Peta_FF10;
extern lv_obj_t * ui_Waktu10;
extern lv_obj_t * ui_Sound10;
extern lv_obj_t * ui_Brightness10;
extern lv_obj_t * ui_Setting10;
extern lv_obj_t * ui_Personal_setting10;
extern lv_obj_t * ui_Group_setting10;
extern lv_obj_t * ui_radio_setting10;
extern lv_obj_t * ui_logo_intercom10;
extern lv_obj_t * ui_popup_setting10;
extern lv_obj_t * ui_Label_Setting10;
void ui_event_Button_Performance2(lv_event_t * e);
extern lv_obj_t * ui_Button_Performance2;
void ui_event_Button_Selftest2(lv_event_t * e);
extern lv_obj_t * ui_Button_Selftest2;
void ui_event_Button_About2(lv_event_t * e);
extern lv_obj_t * ui_Button_About2;
extern lv_obj_t * ui_Label_Information;
extern lv_obj_t * ui_Label_software;
extern lv_obj_t * ui_Label_Version;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_value_versi;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lucide_server_png);    // assets/lucide_server.png
LV_IMG_DECLARE(ui_img_1559931635);    // assets/majesticons_sound-up.png
LV_IMG_DECLARE(ui_img_388315622);    // assets/fluent_brightness-low-28-filled.png
LV_IMG_DECLARE(ui_img_111514558);    // assets/ci_settings-filled(1).png
LV_IMG_DECLARE(ui_img_personal_button_png);    // assets/PERSONAL BUTTON.png
LV_IMG_DECLARE(ui_img_group_button_png);    // assets/GROUP BUTTON.png
LV_IMG_DECLARE(ui_img_radiopa_button_png);    // assets/RADIOPA BUTTON.png
LV_IMG_DECLARE(ui_img_logo_navysis_png);    // assets/LOGO NAVYSIS.png
LV_IMG_DECLARE(ui_img_popup_set_png);    // assets/POPUP SET.png
LV_IMG_DECLARE(ui_img_430847109);    // assets/Button Performance(1).png
LV_IMG_DECLARE(ui_img_1693904590);    // assets/Selftest(2).png
LV_IMG_DECLARE(ui_img_650324235);    // assets/About(2).png
LV_IMG_DECLARE(ui_img_1015138501);    // assets/INTERKOM-KRI__2_-removebg-preview.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
